### ISSUE TITLE
Where are the settings?

### ISSUE THREAD

**Issue by NiceGlassesDude** [pythongosssss/ComfyUI-Custom-Scripts#104]
I don't quite understand the guide unfortunately. Where are the custom prompt settings etc. ?

**Comment by TheFinchMachine** [comment]
For all the people who have this same problem in the future. Its the gear button on the side panel
![Screenshot_20241005_203621-1](https://github.com/user-attachments/assets/57ac94cd-a904-4d8c-b22e-fa012c703ab5)
