### ISSUE TITLE
[Feature Request] Arrow key shortcut for cycling through image feed

### ISSUE THREAD

**Issue by GruvoSmack** [pythongosssss/ComfyUI-Custom-Scripts#116]
Would it be possible to add arrow key shortcut to cycle left and right through image feed images? It's pretty standard for this type of image galleries and I think it would be useful small QOL add. Thanks

**Comment by pythongosssss** [comment]
Thanks @DrJKL for implementing this
https://github.com/pythongosssss/ComfyUI-Custom-Scripts/pull/112
