### ISSUE TITLE
Couple autocomplete issues

### ISSUE THREAD

**Issue by Kahldris** [pythongosssss/ComfyUI-Custom-Scripts#117]
1. Unlike the A1111 autocomplete it keeps the underscores in the prompts, I checked to see if it changes the output much, and it kinda does. Should I be manually fixing the prompt each time with spaces, since most models seem to recommend not using underscores?

2. I copied the [3M Fluffyrock tags](https://cdn.discordapp.com/attachments/1086767639763898458/1118193087118852276/fluffyrock_3m.csv?ex=655cc5f6&is=654a50f6&hm=0f108ba00f2eda599f74af27dfbbcef69f5115802f437f4e8a2472760f8211a8&) from the csv to the autocomplete txt, I thought the format should work because of https://github.com/pythongosssss/ComfyUI-Custom-Scripts/issues/71. Some tags autocomplete properly, but some don't show up. Like "by_chunie", or "fountain" for a random example doesn't pop up anything, but there's 9 tags that have the word fountain in the file. Actually there's thousands of "by_artist" in the file but none of them seem to autocomplete for me.

Thanks!

**Comment by EricRollei** [comment]
Adding to this:   The setting for autocomplete from the manager doesn't stick.  It's always enabled on a new browser tab and after every start.  Secondly, when opening the settings in the manager, the autocomplete will show that it's not enabled when it is, so you have to click it on, and then click it off to disable it.

**Comment by EricRollei** [comment]
A 3rd issue for autocomplete is that it should be outside the text area, not inside, or in my case because of monitor scaling always hovering over where I am typing. Is it possible for it to be set to be active just below the text box instead of right on it?  Maybe too much work or not possible with the software used for the graph?

**Comment by toyxyz** [comment]
> A 3rd issue for autocomplete is that it should be outside the text area, not inside, or in my case because of monitor scaling always hovering over where I am typing. Is it possible for it to be set to be active just below the text box instead of right on it? Maybe too much work or not possible with the software used for the graph?

I agree with this - often the list covers the text or is moved away from it.

**Comment by pythongosssss** [comment]
I've fixed the enabled setting, updated positioning to take canvas scaling into account when positioning and added a setting to replace _ with space

**Comment by pythongosssss** [comment]
Closing this as I think all the issues here are fixed, if not please reopen/log any new issues
