### ISSUE TITLE
“ReferenceError: resolve is not defined” when loading JPEG files

### ISSUE THREAD

**Issue by palant** [pythongosssss/ComfyUI-Custom-Scripts#123]
This came up in https://github.com/palant/extended-saveimage-comfyui/issues/2, there is a bug here:

https://github.com/pythongosssss/ComfyUI-Custom-Scripts/blob/27555d4f71bb4e24b87571f89eab2b4a06677bb6/web/js/workflowImage.js#L390-L406

This function calls `resolve()` four times when the variable in question is actually called `r`.

**Comment by pythongosssss** [comment]
This should be fixed
