### ISSUE TITLE
[FEATURE REQ] Store user config in file vs browser

### ISSUE THREAD

**Issue by revolvedai** [pythongosssss/ComfyUI-Custom-Scripts#125]
Hello! Big fan of your scripts. They are useful.

They autocomplete drives me batty however! I don't use it and it pops up and interrupts my prompting. I want to disable it for all the folks who use comfyui on our servers but there is no file configuration. Only browser side. Is it possible you could build in the ability for the config settings to reference and be stored in a file? Then it could be set for every new instance of comfyui that is booted.

Thank you for the great scripts!

**Comment by pythongosssss** [comment]
This will be done once i've finished my updates to make the same changes for the main repo! Hopefully I'll get that finished soon™️

**Comment by revolvedai** [comment]
Checking back in on this, any chance this could be added (or already has been added?)

**Comment by pythongosssss** [comment]
The "enabled" flag for the autocomplete is stored on the server settings, for a single user setup this is located:
`ComfyUI\user\default\comfy.settings.json`

You can have your instances update that file to include 
`"pysssss.AutoCompleter": false`

I haven't moved the other autocomplete settings into there but this is the main one causing your issues i'd imagine?
