### ISSUE TITLE
Save Text node not working at all.

### ISSUE THREAD

**Issue by RangerFrank** [pythongosssss/ComfyUI-Custom-Scripts#126]
Save Text node not working at all, doesn't create or append or modify any text file no matter the parameters.

**Comment by RangerFrank** [comment]
ERROR:root:Failed to validate prompt for output 130:
ERROR:root:* SaveText|pysssss 127:
ERROR:root:  - Exception when validating inner node: TextFileNode.VALIDATE_INPUTS() missing 1 required positional argument: 'file'
ERROR:root:Output will be ignored

**Comment by Wraithnaut** [comment]
'SaveText|pysssss' works fine until you try converting the 'file' widget to input, which is how I came across the error message RangerFrank reported. 

### Steps to replicate:

1. Add the 'SaveText|pysssss' node to the workflow area. 
2. Convert the 'file' widget to an input
3. (Connect a string output * and queue prompt and see the error: - Exception when validating inner node: No file" *)
4. Convert 'file' back to a widget.
5. Queue prompt (again) and see the same error RangerFrank saw: - Exception when validating inner node: TextFileNode.VALIDATE_INPUTS() missing 1 required positional argument: 'file'

* The string outputs I tried were 'filename_text' from 'Load Image Batch' and 'STRING' from 'StringFunction|pysssss'
* Step 3 is optional and is likely a related but separate issue.

### Work around: 
Create a fresh copy of 'SaveText|pysssss' and replace it for the bugged node and it worked again for me. For science I tried a cloned copy of the bugged node but it triggered the same errors. Only a fresh instance of 'SaveText|pysssss' will allow you to fix the workflow.

### Complete Error Messages from the terminal
Error when 'file' is input:

> got prompt
> ERROR:root:Failed to validate prompt for output 37:
> ERROR:root:* SaveText|pysssss 40:
> ERROR:root:  - Exception when validating inner node: No file
> ERROR:root:Output will be ignored

Error after converting 'file' back to widget:
> got prompt
> ERROR:root:Failed to validate prompt for output 37:
> ERROR:root:* SaveText|pysssss 40:
> ERROR:root:  - Exception when validating inner node: TextFileNode.VALIDATE_INPUTS() missing 1 required positional argument: 'file'
> ERROR:root:Output will be ignored

**Comment by RangerFrank** [comment]
Thanks for your insight, I'm avoiding the error but still not getting a result. No text file creation, no overwrite or append working on existing text files.

[savetext.json](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/files/13541276/savetext.json)

**Comment by Wraithnaut** [comment]
Manually set the file name and don't swap 'file' to input and the rest of the Save Text node should work fine. If manually setting the file name is an issue due batch processing, you'll need to try out other custom nodes until this is fixed.

**Comment by pythongosssss** [comment]
This should be fixed 
![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/125205205/44d696e5-1bd9-4790-9466-8ff6d1b907aa)
