### ISSUE TITLE
'SaveText|pysssss' node: Converting 'file' to input triggers an error

### ISSUE THREAD

**Issue by Wraithnaut** [pythongosssss/ComfyUI-Custom-Scripts#127]
'SaveText|pysssss' node instances work properly until you try to convert 'file' from a widget to an input, after which that node is bugged and won't work again. New instances are unaffected but will experience the same error if you convert their 'file' to an input.

> 'See linked post in issue 126:  
>
>_Originally posted by @Wraithnaut in https://github.com/pythongosssss/ComfyUI-Custom-Scripts/issues/126#issuecomment-1837575409_

The string outputs I tried connecting to 'file' as input were 'filename_text' from 'Load Image Batch' and then for science I tried using the 'STRING' output from 'StringFunction|pysssss' as an intermediary but with the same results.

I don't have a workaround for using 'file' as input. New instances of  'SaveText|pysssss' work fine as long as you don't convert 'file' from a widget.

### Complete Error Messages from the terminal when 'file' is a connected input.

> got prompt
> ERROR:root:Failed to validate prompt for output 37:
> ERROR:root:* SaveText|pysssss 40:
> ERROR:root:  - Exception when validating inner node: No file
> ERROR:root:Output will be ignored

**Comment by pythongosssss** [comment]
This should be fixed 
![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/125205205/44d696e5-1bd9-4790-9466-8ff6d1b907aa)

**Comment by Wraithnaut** [comment]
Awesome! Love your custom nodes.
