### ISSUE TITLE
BUG: Extension interferes with other extensions ability to save workflow into webp format

### ISSUE THREAD

**Issue by Dachiko** [pythongosssss/ComfyUI-Custom-Scripts#128]
While custom scripts enabled, other extensions fail to save workflow in webp format (png possibly affected too, can't confirm, don't use png)

**Comment by pythongosssss** [comment]
Do you have any additional information?

**Comment by Dachiko** [comment]
Unfortunately no. Was trying to establish jpg or webp as a working standard for me, tried different image save nodes, but none of them was able to save the workflow inside images. Later some Reddit user said he had same issue and that this extension prevents saving the workflows. I disabled it too, and it solved the issue indeed. Don't use Custom-Scripts since :(

**Comment by pythongosssss** [comment]
Do you know what other extension it was conflicting with so I can look at the code

**Comment by Dachiko** [comment]
It was a month ago, don't remember the names, but I remember trying all image saving nodes which I could find (with jpg/webp ability), and none of them were able to save the workflow. I'm sorry I can't back it up at this point.
Actually, just looked up and found the Reddit thread where we discussed the matter: https://www.reddit.com/r/StableDiffusion/comments/188tre9/comment/kbn0ay6/?utm_source=share&utm_medium=web2x&context=3

**Comment by pythongosssss** [comment]
OK thanks, i've tested that node and the crash is resolved

**Comment by Dachiko** [comment]
Thank you!
