### ISSUE TITLE
Feature request: autocomplete options for LoRA

### ISSUE THREAD

**Issue by TomLucidor** [pythongosssss/ComfyUI-Custom-Scripts#131]
Borrowing ideas from badjeff, there is a "load LoRA from sting" option for testing prompts in the A1111 format, but ComfyUI does this differently. Right now the autocomplete only handles embeddings https://github.com/badjeff/comfyui_lora_tag_loader

**Comment by xieve** [comment]
I'm currently using rgthree's Power Prompt node for this, but that means I'm still missing the view info button (which could work exactly the same as for the embeddings)

**Comment by pythongosssss** [comment]
This is now supported via a setting thanks to @qrtal
https://github.com/pythongosssss/ComfyUI-Custom-Scripts/pull/156
