### ISSUE TITLE
show text node not work properly

### ISSUE THREAD

**Issue by liulsg** [pythongosssss/ComfyUI-Custom-Scripts#133]
show text node not work properly
ComfyUI Revision: 1779 [9b655d4f]
Browser: Google
![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/97494068/69742ceb-dbf9-4d04-ba68-cbc29e1dcf5b)

**Comment by pythongosssss** [comment]
Assuming this is on reload of a workflow, this should be fixed
