### ISSUE TITLE
[FEATURE REQUEST] Checkpoint/LoRA/Embedding Info working with Efficient Loader node

### ISSUE THREAD

**Issue by alessandroperilli** [pythongosssss/ComfyUI-Custom-Scripts#135]
The `Checkpoint/LoRA/Embedding Info` feature is amazingly useful. Not sure if it's technically possible, but it would be great if it would work with `Efficient Loader` nodes, too. 

Thank you for considering the request.

**Comment by Neurai-ai** [comment]
I agree, I would love to use this as part of my XYZ workflow.

**Comment by pythongosssss** [comment]
I don't have these nodes installed and i'm "trying" to keep this install as clean as possible so i've guessed what the nodes types are - if it doesnt work or there are other nodes let me know

I've added:
	"Efficient Loader": "checkpoints",
	"Eff. Loader SDXL": "checkpoints",

**Comment by alessandroperilli** [comment]
It works in almost every scenario, thank you!

When it does NOT work:

<img width="1211" alt="Screenshot 2024-01-05 at 08 22 12" src="https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/9775949/1f140bdb-5fac-489b-9f63-709ae8c13010">

In this case, the `ckpt_name` input is external, passed by another node. When this happens, the `View Info` command loads the information for a random (?) other checkpoint I have in my folder.
