### ISSUE TITLE
Can PlaySound support incoming sound addresses?

### ISSUE THREAD

**Issue by zhu-dq** [pythongosssss/ComfyUI-Custom-Scripts#136]
The scenario is: I hope that the dynamically generated MP3 file can play sou

**Comment by pythongosssss** [comment]
Its now possible to use them from any URL so you can have an endpoint that returns the mp3
![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/125205205/33802bb6-9fff-4c62-ab0a-bab3dc5a5576)

**Comment by stephantual** [comment]
Great! Now i can hear  my own voice while I generate images :)
