### ISSUE TITLE
After right-clicking on a single machine, saving the workflow and loading the workflow did not appear. This problem occurred after just updating comfyui and all updates.

### ISSUE THREAD

**Issue by wibur0620** [pythongosssss/ComfyUI-Custom-Scripts#138]
After right-clicking on a single machine, saving the workflow and loading the workflow did not appear. This problem occurred after just updating comfyui and all updates.

https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/131615326/672b9fb4-01f4-4c44-b60c-36dd3b059b48

**Comment by wibur0620** [comment]
The issue arose due to a conflict with the "comfyui-mixlab-nodes" plugin. After removing the "comfyui-mixlab-nodes" plugin, everything returned to normal.

https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/131615326/e86d3bf4-48b0-42e7-9977-d72e2a60cf17

https://github.com/shadowcz007/comfyui-mixlab-nodes

**Comment by wibur0620** [comment]
https://github.com/shadowcz007/comfyui-mixlab-nodes/issues/53

**Comment by pythongosssss** [comment]
Reported as fixed in the other repo! (y)
