### ISSUE TITLE
Image Feed Viewer Request 

### ISSUE THREAD

**Issue by MaisonMeta** [pythongosssss/ComfyUI-Custom-Scripts#139]
Not too much an issue but more of a small request. 

On the image feed viewer, could we add simple hotkeys such as: 
Esc to exit the image popup 
right and left arrow keys to navigate between images. 

It will be super useful instead of clicking arrows, especially if you have large screens...

**Comment by stephantual** [comment]
I think this is the type of thing we must code by ourselves - and for good measure submit a PR :) It's early days in this space :)

**Comment by pythongosssss** [comment]
Thanks @DrJKL for implementing this
https://github.com/pythongosssss/ComfyUI-Custom-Scripts/pull/112
