### ISSUE TITLE
[Feature Request] Switching position of the preview gallery to any side of the page

### ISSUE THREAD

**Issue by aphaits** [pythongosssss/ComfyUI-Custom-Scripts#14]
currently its nicely on the bottom part of the browser page, but it would be really helpful if you toggle it to a left vertical scroll also.

I imagine the options would be:
1. Default bottom row
2. Left vertical
3. Right vertical
4. Top row
5. maybe detached and moveable like the main comfyui toolbar? with resizing capabilities?
6. reversing the order from new-to-old to old-to-new

**Comment by pythongosssss** [comment]
I've added settings to the comfy settings screen for location + direction
![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/125205205/17baaf65-be8a-41f5-8102-df871a1c8668)

Resizing the panel horizontally is a bit buggy as the resizer fights with the size, i'll need to revisit that in future
