### ISSUE TITLE
check if extra_pnginfo is not None

### ISSUE THREAD

**Issue by xingren23** [pythongosssss/ComfyUI-Custom-Scripts#141]
sometime the execution context could not include extra_pnginfo, maybe we could check it is not None

def evaluate(self, expression, extra_pnginfo, prompt, a=None, b=None, c=None):
    expression = expression.replace('\n', ' ').replace('\r', '')
    node = ast.parse(expression, mode='eval').body

    lookup = {"a": a, "b": b, "c": c}

    def eval_expr(node):
        ....
        elif isinstance(node, ast.Attribute):
            if node.value.id in lookup:
                if node.attr == "width" or node.attr == "height":
                    return self.get_size(lookup[node.value.id], node.attr)

            return self.get_widget_value(extra_pnginfo, prompt, node.value.id, node.attr)
        ....

**Comment by pythongosssss** [comment]
Done!
