### ISSUE TITLE
[Feature request]: PlaySound: selectable sound files

### ISSUE THREAD

**Issue by Woisek** [pythongosssss/ComfyUI-Custom-Scripts#143]
I find the PlaySound node incredible useful. As my workflows grow more complex, I would love to have the possibility to use the PlaySound node on various stages in the workflow. And with that, it would be fantastic if we could select a mp3 file from a list that then is played (i.e. from a defined folder where mp3s are saved).
So, when my workflow has like 2 "checkpoints", I would use i.e. beep1.mp3 on the first and beep2.mp3 on the second. This way, I could distinguish audibly in what stage the workflow is at the current time.
I would really love to have this possibility, please. 🙂

**Comment by pythongosssss** [comment]
I've added this so you can put multiple files in the assets folder and use the name, or you can use URLs if the website allows cross domain access.
![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/125205205/33802bb6-9fff-4c62-ab0a-bab3dc5a5576)

**Comment by Woisek** [comment]
That's awesome, but somehow, I don't get it after updating. Any ideas what happened? 🤔

**Comment by stephantual** [comment]
I'm 100% sure someone is building a simple tracker in Comfy at this point :) 
(this is a joke, i need a joke font).
PS: good suggestion. I use it to record my voice and guide me through a 15 step process. this could also hep those with disabilities using this tool.
