### ISSUE TITLE
Make "play sound" a passthrough

### ISSUE THREAD

**Issue by Immac** [pythongosssss/ComfyUI-Custom-Scripts#144]
This would ensure the moment the sound is played is less affected by the order of execution. My most common use case for this is just before an image chooser, sometimes if I don't take good care of connecting the nodes in a certain way the play-sound will play after choosing the picture and not before.

**Comment by pythongosssss** [comment]
I've added this as an untyped output
![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/125205205/33802bb6-9fff-4c62-ab0a-bab3dc5a5576)
