### ISSUE TITLE
Middle click default doesn't default to the correct option.

### ISSUE THREAD

**Issue by stephantual** [pythongosssss/ComfyUI-Custom-Scripts#146]
To reproduce:
* install a few extensions that have a reroute module, such as RGthree, 0246 etc.
* set 'middle click defaults to X (RGthree in my case)
* middle click drag and you get a default reroute, NOT the rgthree (or any selected) version.

Not a huge deal but would be useful if fixed given we do a lot of reroute in comfy :) 

Thank you!

**Comment by pythongosssss** [comment]
Not sure what you mean by middle click drag?

**Comment by stephantual** [comment]
Thank you @pythongosssss , the last update fixed it - i mean 'middle mouse button' (wheel button) - was creating the wrong kind of reroutes, but now it does - very happy !
