### ISSUE TITLE
Extract ckpt_name from Checkpoint Loader Node

### ISSUE THREAD

**Issue by ghostsquad** [pythongosssss/ComfyUI-Custom-Scripts#150]
Hi! I'm trying to extract the checkpoint name from the Checkpoint Loader node, and running into an issue where the value of the combo box is actually a JSON object (checkpoint path and image path).

Do you know how I might extract the "content" field from this?

Alternatively, can you add the ckpt_name as an output on this node?

Thanks for your time!

![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/903488/757efb9c-7d0f-4e8d-a55d-2663ee56cbc0)

![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/903488/e2cb37d9-2cc8-4b2c-8044-b8a8f8de70a8)

**Comment by pythongosssss** [comment]
![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/125205205/d8a98bc9-eaeb-4ed6-b770-cc3edaeeb1a1)

`/.*content":\s+\"([^"]+)"(.|\s)*/`
you can try this to extract it

**Comment by ghostsquad** [comment]
Ya, I wanted to do something that wasn't text parsing

**Comment by ghostsquad** [comment]
The actual issue actually, is that I have to use the "read widget" node. This is problematic because node numbers can change, and I'd really like to show the explicit connection (output).

**Comment by ghostsquad** [comment]
closing this, as I realized that the modification to the node here is modifying the default node coming from ComfyUI upstream. I'll make a PR to ComfyUI.

**Comment by Neytiri7** [comment]
`{'content':` I hope it's only detected after the item...
