### ISSUE TITLE
[BUG] Excess space in exported workflow images

### ISSUE THREAD

**Issue by MalikKillian** [pythongosssss/ComfyUI-Custom-Scripts#153]
Took me a while to figure out why I was getting a lot of empty space in my exported workflow images. Up to now the feature has been quite solid.

Near the bottom of one of my workflows is smZ Settings Node. This node is quite big so I try to keep it collapsed. However, the export function seems to expand the image to account for the full size of this node. From the examples below you can see the function is indeed accounting for the full size of the node.

Export with node collapsed:
![workflow](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/3229684/fde34af9-3b92-4e8d-b18e-58279618b7fb)

Export with node uncollapsed/normal:
![workflow (3)](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/3229684/4c021866-b922-4fb9-9e01-2f363c055e93)

**Comment by pythongosssss** [comment]
This should now be fixed
