### ISSUE TITLE
Embedding Prompt Autocomplete has a 'View Info' button for each embedding but nothing appears on hover or click?

### ISSUE THREAD

**Issue by Wraithnaut** [pythongosssss/ComfyUI-Custom-Scripts#158]
I am curious about the blue 'View Info' button that appears next to embeddings during embedding prompt autocomplete. I imagine it looks like the checkpoint and lora 'View info', which are working for me, but currently nothing happens when I click on or hover over these buttons. 

Tested on Opera and Firefox on Linux. 
ComfyUI Revision: 1885 [c6951548] | Released on '2024-01-07'

Appreciate your time and work on these great features.

**Comment by pythongosssss** [comment]
It should open up the Civitai info for the embedding, e.g.
![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/125205205/7ad13f5c-1cc8-4909-b0f5-7340fa9db0e1)

Could you please check if there are any errors in your browser console or in the logs (Settings cog on the menu -> View Logs) when you load up/click the button (F12 will open the browser dev tools)

**Comment by Wraithnaut** [comment]
We can go ahead and mark this as closed. I tried again recently and let it sit there and it started working. Not sure if it is my internet or something on Civitai's end but there were no errors in the console.
