### ISSUE TITLE
[issue] Uncaught TypeError: workflows.workflows is not iterable

### ISSUE THREAD

**Issue by dev2pew** [pythongosssss/ComfyUI-Custom-Scripts#159]
## Description
Installed as usual according to the instructions: `git clone https://github.com/pythongosssss/ComfyUI-Custom-Scripts.git`

- Windows 10 21H2
- Python 3.11.0

## Problems
- ⚙️ settings won't open after installing `custom-scripts`:
![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/65161490/c843f4f1-e5f1-4079-b5ab-de8865b6acb9)
![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/65161490/40fdb74b-9a48-4ac1-8b9b-adb21cad8200)

- can't use "Save to workflows" option in Save:
![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/65161490/ae5c9820-02f1-452f-ac6c-9607d7947094)
![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/65161490/003a15a5-40da-4896-8b0e-268c82d5e476)

- custom nodes are missing:
![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/65161490/56d7707a-de59-4e38-b809-3a6f2f6dcad9)
![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/65161490/5a669d14-bcc1-4cc4-b872-8f5ca59cc4d7)

---

I've tried updating `comfyui`, its dependencies and node itself, but no result;
I've tried reinstalling `comfyui` (both standalone and regular), no result;
I've tried reinstalling `custom-scripts`, still no result.

---

I suspect the node fails to download the rest of the files, as the node folder takes less than 1 MB:
![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/65161490/5c05eaac-ffab-46e8-9413-e61f7daabc92)

**Comment by pythongosssss** [comment]
Do you have an error in the ComfyUI console window when you start up? Looks like the route arent being added to the server correctly

**Comment by dev2pew** [comment]
> Do you have an error in the ComfyUI console window when you start up? Looks like the route arent being added to the server correctly

I checked the logs and found nothing. The problem still persists. Any suggestions, please?
[comfyui.log](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/files/14322673/comfyui.log)

**Comment by pythongosssss** [comment]
I would recommend using the new beta menu & workflow management in ComfyUI. This feature has been deprecated by the comfyui core feature.
