### ISSUE TITLE
Unable to pass strings/text properly to String Function

### ISSUE THREAD

**Issue by ghostsquad** [pythongosssss/ComfyUI-Custom-Scripts#164]
I'm trying to setup some nodes to do a dynamic string/text replacement, however, I'm running into what I think is maybe an escaping issue:

here's is the default/working use case:

![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/903488/d62bd7e9-c4cf-415f-9cfb-75eaeea10b9a)

However if I _pass_ in the text for `text_c`, the behavior changes.

![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/903488/fa62a828-c1b0-4442-9dac-f65f095e3080)

Any help on this would be appreciated!

**Comment by pythongosssss** [comment]
![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/125205205/bb10c6af-d915-4051-b7c6-4a8320521aa2)
I'm not able to recreate this issue using primitive nodes, it may be another extension doing something?

**Comment by ghostsquad** [comment]
ya, might be the CR node. I'll use a primitive node.
