### ISSUE TITLE
Bug:`Replace _ with space` will cause `lora-text` and `embeding-text` to be invalid

### ISSUE THREAD

**Issue by mijuku233** [pythongosssss/ComfyUI-Custom-Scripts#165]
Enabling `Replace _ with space` will cause the autocomplete of `lora-text` and `embeding-text` to be invalid (when the text contains _), and the comma inserted by `Auto-insert comma` is unnecessary for `lora-text`, which will resulting in different results

correct result:
![屏幕截图 2024-01-18 164519](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/89350747/93c572da-ae32-4436-809e-79b182be9542)

unnecessary comma:
![屏幕截图 2024-01-18 164539](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/89350747/2674a76b-250b-4b08-89cc-762c2d274bb6)

Invalid lora:
![屏幕截图 2024-01-18 164614](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/89350747/7349b098-94e0-4ce6-b1a6-c2e2a8609b5d)

Invalid embedding:
![屏幕截图 2024-01-18 164659](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/89350747/45438349-71b4-4891-8ee9-658ddc6eca2c)

**Comment by Mossbraker** [comment]
I have 'Replace _ with space' disabled, but it still replaces _ with space anyway and causes lora-text to be invalid
