### ISSUE TITLE
Can‘t open comfyui setting windows

### ISSUE THREAD

**Issue by meisekiyou** [pythongosssss/ComfyUI-Custom-Scripts#167]
When I install this plug, I can't open the comfyui settings window.

Comfyui Version: new_ComfyUI_windows_portable_nvidia_cu121_or_cpu

**Comment by pythongosssss** [comment]
Can you please press F12 in your browser to get the dev tools open, then see if there are any errors in the console

**Comment by meisekiyou** [comment]
ui.js:38 Uncaught TypeError: Spread syntax requires ...iterable[Symbol.iterator] to be a function
    at $el (ui.js:38:13)
    at type (autocompleter.js:474:9)
    at Object.render (settings.js:151:16)
    at settings.js:303:79
    at Array.map (<anonymous>)
    at ComfySettingsDialog.show (settings.js:303:66)
    at HTMLButtonElement.onclick (ui.js:364:87)

**Comment by pythongosssss** [comment]
I think you're running an older version of ComfyUI (the release zips arent 100% latest)
I've done an update to make it work with older versions

**Comment by meisekiyou** [comment]
It's worked.
Thanks
