### ISSUE TITLE
Allow customization of icon

### ISSUE THREAD

**Issue by Praecordi** [pythongosssss/ComfyUI-Custom-Scripts#169]
It's not terribly important, but is it possible to add some script to allow us to customize the icons? The current method I use is changing the favicon.ico and favicon-r.ico, but this is overridden by the default icons every time I update comfyUI (through the manager). Is this possible?

**Comment by pythongosssss** [comment]
You can now put `web/js/assets/favicon.user.ico` and `web/js/assets/favicon-active.user.ico`
![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/125205205/9f352f58-7491-4899-83a3-bdd5fbe47c57)
