### ISSUE TITLE
[FEATURE REQUEST] LoRA info for LoRA Stacker

### ISSUE THREAD

**Issue by wirep95326** [pythongosssss/ComfyUI-Custom-Scripts#171]
LoRA Stacker of the [Efficiency nodes](https://github.com/jags111/efficiency-nodes-comfyui) repo is able to select/load x amount of loras and it would be very useful if the LoRA info function would support the node. The node looks like this.

![LoRA Loader](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/135263005/4dd958b2-785f-4450-ab19-09c4cf23bc2a)

Thanks in advance!

**Comment by marduk191** [comment]
So this is a feature request for an completely different node pack lol

**Comment by pythongosssss** [comment]
You can use this 
`LoraLoader.lora_name,LoraLoader|pysssss,LoraLoaderModelOnly.lora_name,LoRA Stacker.lora_name.*`
In the setting called _🐍 Model Info - Lora Nodes/Widgets_

This should add support for the stacker, and you can add support for other nodes in the same manner.
