### ISSUE TITLE
Text is 'undefined' for Multiline Text inputs

### ISSUE THREAD

**Issue by nidefawl** [pythongosssss/ComfyUI-Custom-Scripts#172]
When converting a multiline-text widget back to a widget the text is always serialized to "undefined".

This is because the callbacks list here is never updated here:
https://github.com/pythongosssss/ComfyUI-Custom-Scripts/blob/51c138378eeb6c57a0c2cae9cee7ccbfc550f08a/web/js/presetText.js#L199-L201

The serialize function is swapped back when turning a text-input back into a widget:

https://github.com/comfyanonymous/ComfyUI/blob/d1533d9c0f1dde192f738ef1b745b15f49f41e02/web/extensions/core/widgetInputs.js#L51-L55

This also causes disconnected text-inputs to not error out, but serialize to 'undefined'.

I am not sure how to fix this. I worked around it by removing the presetText.js file from my installation.

**Comment by pythongosssss** [comment]
This should now be fixed thanks to @Lawrr
