### ISSUE TITLE
View info window is messed up for all checkpoints and loras

### ISSUE THREAD

**Issue by koko93s** [pythongosssss/ComfyUI-Custom-Scripts#173]
The formatting for the view info window is messed up.  See image below:

![Screenshot (65)](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/36585095/b4f79ba7-17da-4e8e-887a-6c1c65ff5b3c)

**Comment by koko93s** [comment]
Discovered this issue is a conflict between the css for this extension and the one from [https://github.com/syllebra/bilbox-comfyui](url).  The css from bilbox is overriding the styles set by this extension.

**Comment by pythongosssss** [comment]
That extension is changing things very widely, not something I can really fix, e.g.

https://github.com/syllebra/bilbox-comfyui/blob/8ed53fe26a863c1920743f38790e3f5f96580cf4/web/bilbox.css#L73C1-L73C19
here it is moving every span on every modal to the top right

**Comment by koko93s** [comment]
Thanks, I’ll chase it down with the other extension!  Appreciate you looking at it.Sent from my iPhoneOn Jan 31, 2024, at 2:49 PM, pythongosssss ***@***.***> wrote:﻿
That extension is changing things very widely, not something I can really fix, e.g.
https://github.com/syllebra/bilbox-comfyui/blob/8ed53fe26a863c1920743f38790e3f5f96580cf4/web/bilbox.css#L73C1-L73C19
here it is moving every span on every modal to the top right
