### ISSUE TITLE
Please Fix asyncio Error

### ISSUE THREAD

**Issue by Soliver84** [pythongosssss/ComfyUI-Custom-Scripts#175]
LOGS:
[log.txt](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/files/14070125/log.txt)
![Shot](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/11579411/df9e4051-09db-493d-85de-b2312c4ac2de)

**Comment by pythongosssss** [comment]
Are you trying to use https? There is this error here which seems related:
https://github.com/home-assistant/core/issues/45641

  File "asyncio\base_events.py", line 268, in restore
  File "asyncio\sslproto.py", line 343, in resume_reading
AttributeError: 'NoneType' object has no attribute 'resume_reading'

im sure how this repo could be causing the error
