### ISSUE TITLE
Text Autocomplete settings are missing in StableSwarmUI and Autocomplete does not function

### ISSUE THREAD

**Issue by bWm-nubby** [pythongosssss/ComfyUI-Custom-Scripts#179]
OS: Windows 11
Python Version: 3.10.11
ComfyUI installed manually (not portable zip)
ComfyUI, StableSwarmUI, ComfyUI-Custom-Scripts, and all other installed custom nodes updated to latest versions.

When loading ComfyUI separately the Text Autocomplete options are available and it functions as expected. 

In StableSwarmUI (Comfy Workflow Editor tab) the Text Autocomplete options are missing from the settings menu and Autocomplete does not work at all. Other ComfyUI-Custom-Scripts features seem to be present in the settings menu and function correctly as far as I can tell. 

![Screenshot 2024-01-30 145855](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/130875789/0e533236-6ae8-4c00-a820-28d5be349d30)

Possible related PR: #149

**Comment by pythongosssss** [comment]
Would you be able to check the log to see if there are any errors (the View Logs in settings) or send me a copy so I can take a look please.

**Comment by bWm-nubby** [comment]
> Would you be able to check the log to see if there are any errors (the View Logs in settings) or send me a copy so I can take a look please.

Sure, here are the full logs in case it's helpful. As a side note logging was enabled to begin with but displayed "logging is disabled" at the top of the logs. I had to toggle logging off then back on and refresh the webpage to get the logs to appear.

[comfyui-logs-1706816229568.json](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/files/14129989/comfyui-logs-1706816229568.json)

Relevant error:
```
error
19:36:20.248Z
[
  "Error loading extension",
  "/extensions/ComfyUI-Custom-Scripts/js/autocompleter.js",
  "TypeError\nFailed to fetch dynamically imported module: http://localhost:7801/ComfyBackendDirect/extensions/ComfyUI-Custom-Scripts/js/autocompleter.js\nTypeError: Failed to fetch dynamically imported module: http://localhost:7801/ComfyBackendDirect/extensions/ComfyUI-Custom-Scripts/js/autocompleter.js\n"
]

```

**Comment by pythongosssss** [comment]
If you could please press F12 to open the browser console, then click on the Network tab
Reload the page, and see which request is failing

**Comment by bWm-nubby** [comment]
I'm not sure exactly what I'm looking for in there. If this isn't what you need just let me know where to find it in there and I'll grab another screen.

![Screenshot 2024-02-04 213028](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/130875789/e2421bde-52ec-4b7d-ba3b-ab73e20e2e3f)

**Comment by pythongosssss** [comment]
At the top, where it says "Network", if you could see if there are any failed requests related to autocomplete on there please.
Also if you could check the console in Chrome too as sometimes it gives more useful error messages

**Comment by bWm-nubby** [comment]
In Chrome I do not get any errors for autocompleter under the Network tab, only this one for comfy.templates.json
![Screenshot 2024-02-13 114605](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/130875789/9725eb4d-f87a-4ec2-a556-b409d53977c1)

Chrome Console shows the following errors 
![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/130875789/0af3e445-38bb-454e-8270-3f589fb3db7a)

In Firefox I found the following error for autocompleter under the Network tab:
![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/130875789/972869f2-324d-4e23-a2c5-5dc646cfe259)

In Edge I found the following error for autocompleter under the network tab:
![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/130875789/f56e8e81-15ba-43b1-9068-b26523d1aa32)

**Comment by stereosix** [comment]
It appears this is caused due to a couple of extraneous `../`'s in the imports in autocompleter.js.

Since StableSwarmUI is running ComfyUI in a subdirectory (.../ComfyBackendDirect/), these imports are accidentally able to go a directory higher than they normally do / should, and end up not finding the modules they're looking for.

Just put in a PR (#206) that should fix this.
