### ISSUE TITLE
Can i backup the entries from Preset Text node?

### ISSUE THREAD

**Issue by UnclePsymon** [pythongosssss/ComfyUI-Custom-Scripts#181]
Hi, is there a way to i backup the entries from the Preset Text node? They have to be stored somewhere, right? ^^

**Comment by pythongosssss** [comment]
If you press F12 to open the browser console, then type `localStorage["pysssss.PresetText.Presets"]`

**Comment by zmwv823** [comment]
> If you press F12 to open the browser console, then type `localStorage["pysssss.PresetText.Presets"]`

I think he would like a text file that can be backup.
Such as a PresetText.txt in a folder (eg. comfyui/wildcards/PresetText.txt).
