### ISSUE TITLE
Image Feed cannot be disabled on Firfox and  MS Edge

### ISSUE THREAD

**Issue by MrForExample** [pythongosssss/ComfyUI-Custom-Scripts#182]
It's a [quite old issue](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/issues/35#issuecomment-1696472448) now, please fix it 👍 
![Screenshot 2024-02-04 155329](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/62230687/1b45fa7d-e62a-4256-adc6-e5a42ca2d5e5)

**Comment by Da1sypetals** [comment]
a temporary solution can be deleting the menu on top of it in F12 and the red X become visible.

**Comment by pythongosssss** [comment]
This should no longer be an issue with the new comfyui menu
