### ISSUE TITLE
[FEATURE REQUEST] Scrolling on Lora/embed suggestion

### ISSUE THREAD

**Issue by ShalolaAuthor** [pythongosssss/ComfyUI-Custom-Scripts#183]
as the title would say. remembering name hard :(.

**Comment by pythongosssss** [comment]
![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/125205205/65e1fc24-69d1-4b41-94c9-114bbd5cdba9)
I've added a max suggestions, you can set this to a hight number to get a scrollbar
