### ISSUE TITLE
Save workflows inside config folder

### ISSUE THREAD

**Issue by davertor** [pythongosssss/ComfyUI-Custom-Scripts#187]
My problem is that I am running ComfyUI server in a docker container and when the container is stopped, the saved_workflows are deleted (as they are not saved in a persistent folder).

Instead of saving the workflows in the project's root directory, I think you should save them inside the comfyUI config folder, defined in folder_paths.folder_names_and_paths["configs"]. 

The code would be something similar to

```
import folders_path

workflows_directory = os.path.join(folder_names_and_paths["configs"], "pysssss-workflows")
```

**Comment by pythongosssss** [comment]
This feature is now deprecated due to the core comfyui workflow management
