### ISSUE TITLE
When I use the mouse scroll wheel, the image does not move.

### ISSUE THREAD

**Issue by wibur0620** [pythongosssss/ComfyUI-Custom-Scripts#188]
https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/131615326/87cb8c65-ad79-4ed4-9fe1-756835a0fe7e

When I use the mouse scroll wheel, the image does not move.

**Comment by pythongosssss** [comment]
Does this always happen for you or just sometimes? I can't recreate this in Edge (which it looks like looks you're using)

**Comment by pythongosssss** [comment]
No update
