### ISSUE TITLE
Bottom gallery is taking up entire view (and security questions)

### ISSUE THREAD

**Issue by brentjohnston** [pythongosssss/ComfyUI-Custom-Scripts#193]
I believe this custom node was installed from a few workflows that I used when I installed missing custom nodes (or comfyui manager). The problem is randomly during some sessions (this seems random and it doesn't do it each time) A gallery will appear at the bottom and once over 30 generations eventually takes up most of the view. It's pretty instrusive, and took me forever to tie it back to this extension. I am not sure if this is built into comfyui.

How can I get rid of it? Not to be conspiratorial here, but how do we know it's not actually just uploading the stuff we make outside of the cmd window, as share:all was set by default? Does this mean my workflows or images were shared. I got rid of the green share button in comfyui manager settings, but gallery still appears at bottom a lot taking up the view.

I actually don't even have this extension installed, so not sure if some other script tied it into theirs?:
![1](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/23625562/a85d0f68-07cf-43ad-b667-5c8aac6d9756)
this is what it looks like in general:
![2](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/23625562/942c6c22-bc64-459f-906c-a3762ee642a4)

**Comment by brentjohnston** [comment]
I found the clear button for the gallery at bottom, it seems windows display scaling was hiding the red x. I am still not sure if this gallery is a part of comfyui or this node. I'll close issue for now.

**Comment by Shadetail** [comment]
Yes this feature is a part of this custom node pack, it can be toggled on and off by clicking on the little picture icon in the top right corner of the main menu: 
![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/11357447/11d3e990-d2e8-4e16-b3d4-5f0e1e29d047)
