### ISSUE TITLE
[ beautifying ] make groups snap to grid 

### ISSUE THREAD

**Issue by JorgeR81** [pythongosssss/ComfyUI-Custom-Scripts#198]
When I move groups, the node positions don't match the grid anymore. 

So, I need to select and move all the nodes to snap them to the grid again.
And then, I need to "Fit Group to Nodes", to match the group box to the grid.

To make this easier, when the "snap to grid" option is enabled, it should also be applied to groups.

Thanks

**Comment by pvp-by** [comment]
I vote for this improvement

(**PS** _came in to write the same sentence_)

**Comment by pythongosssss** [comment]
This is a core comfyui feature

**Comment by lordwedggie** [comment]
it is not

**Comment by JorgeR81** [comment]
This is now working in Comfy UI core. 
But you need the latest version of the frontend.

https://github.com/comfyanonymous/ComfyUI?tab=readme-ov-file#frontend-development
