### ISSUE TITLE
presetText.js script clashes with nodes in Impact-Pack

### ISSUE THREAD

**Issue by GalaxyTimeMachine** [pythongosssss/ComfyUI-Custom-Scripts#20]
The script in `ComfyUI\web\extensions\pysssss\CustomScripts\presetText.js` causes at leats two nodes in the impact-pack to fail. This was something that was changed recently, but has reverted after updates to the impact-pack. I don't know if this is caused by one or the other, or a combination of both, so I'm logging it here, and I've opened these two for impact-pack:

https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/51
https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/52

**Comment by pythongosssss** [comment]
@GalaxyTimeMachine Looks like this is now resolved by impact pack?
