### ISSUE TITLE
[Feature request]: Autocomplete scrollbar

### ISSUE THREAD

**Issue by dchatel** [pythongosssss/ComfyUI-Custom-Scripts#201]
Is it possible to get a scrollbar in the autocomplete menu, so we can explore the whole range of words instead of the limited range imposed right now?

Similarly to https://github.com/Taremin/webui-monaco-prompt

**Comment by pythongosssss** [comment]
![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/125205205/65e1fc24-69d1-4b41-94c9-114bbd5cdba9)
I've added a max suggestions, you can set this to a hight number to get a scrollbar
