### ISSUE TITLE
String Function regex does not support number quantifier {n}?

### ISSUE THREAD

**Issue by ManOrMonster** [pythongosssss/ComfyUI-Custom-Scripts#202]
I'm trying to make a simple regex replace in String Function that grabs 35 characters and adds cr\newline after. Using the standard number quantifier `{n}` doesn't work, and in fact it seems to ignore curly braces completely.

Using `/(.{35})/` doesn't work:

<img width="424" alt="image" src="https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/3925151/5c9b598e-5174-40e4-a12e-049f6e05831d">

This works, but it's a little unwieldy:

<img width="429" alt="image" src="https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/3925151/e2c92e26-2e3c-4f8b-9954-e4ace4ebd923">

Using, for example, `/(.{5})/`, the output is just the same as using `/(.5)/`:

<img width="563" alt="image" src="https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/3925151/b6fbd102-6c31-4ac8-8d23-71bab05a01a6">

**Comment by pythongosssss** [comment]
This should be fixed
