### ISSUE TITLE
[Feature request] Block preview picture on some Lora/Checkpoints

### ISSUE THREAD

**Issue by zlobniyshurik** [pythongosssss/ComfyUI-Custom-Scripts#205]
Please, add checkbox "block picture preview" in "View Info" for some LORAs/Checkpoints.
If we can edit notes personally for some LORA, then we should be able to set flag - "don't show preview" for that LORA/Checkpoint

"View Info" really cool feature, but some LORAs/Checkpoints has too hot NSFW previews :)

**Comment by pythongosssss** [comment]
I've added a setting for max NSFW level
