### ISSUE TITLE
Regex Quantifier {} not working in String Function node

### ISSUE THREAD

**Issue by UrzasLegacy** [pythongosssss/ComfyUI-Custom-Scripts#211]
![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/95994251/b2698852-ef33-448d-ba90-7060e8bcf08a)

Expected behavior: Appending {4} should match the previous token exactly 4 times.

Actual behavior: Curly braces are just ignored completely :(

P.S. I love your addon! <3

P.P.S. r"(........................................................................................................................................................................................................[\s,])(.*)" is my workaround for now in case anyone else runs into this :P

**Comment by pythongosssss** [comment]
This should be fixed
