### ISSUE TITLE
Load workflow drop down list too narrow 

### ISSUE THREAD

**Issue by stavsap** [pythongosssss/ComfyUI-Custom-Scripts#217]
the drop down list presenting the saved workflows appear too narrow for workflow names resulting in breaking a name in 2 lines.

for example name:

instantid-ip-adapter-face-swap will break into:

instantid-ip-adapter-face-
swap

![Screenshot 2024-03-24 202857](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/4201054/af35b994-e2f5-4acd-b484-e28ba9be0e52)

**Comment by pythongosssss** [comment]
This feature is now deprecated due to the core comfyui workflow management
