### ISSUE TITLE
Not showing text in node after using One Button Prompt.

### ISSUE THREAD

**Issue by S0LTIS** [pythongosssss/ComfyUI-Custom-Scripts#218]
Not showing text in node after using One Button Prompt.
![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/124645295/01f2a4c4-f090-4cf1-a753-df320a44d8c9)

**Comment by AIrjen** [comment]
I can't seem to get the Show Text node to work at all, even without One Button Prompt.

**Comment by WeirdScienceX** [comment]
I just tried it, works fine both with One Button Prompt and others. 
![firefox_PVfI2Ir2Dw](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/1296569/8a4adee4-e22b-4d77-9cef-8b66845729f0)

**Comment by AIrjen** [comment]
Uh, tried again this morning. Now it all looks fine:

![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/130234949/8a2087df-9999-450d-b77c-d77e6ad02694)
