### ISSUE TITLE
text autocomplete not working

### ISSUE THREAD

**Issue by uoo2** [pythongosssss/ComfyUI-Custom-Scripts#219]
The other functions are all right, but the text autocomplete function is not working, and it was fine a few days ago

**Comment by WeirdScienceX** [comment]
I can confirm.

**Comment by Stardesign2024** [comment]
me too

**Comment by pythongosssss** [comment]
Do you have any errors in the logs (Settings -> View Logs)

**Comment by sdk401** [comment]
Can confirm, nothing popping up, no errors in logs.

**Comment by Endebert** [comment]
Had the same issue. Solution was to increase "Max suggestion" setting from 0. I guess this is a new setting?

![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/9431420/13ab9c68-81b0-4c4f-97dd-1a43e77b7ac5)

**Comment by pythongosssss** [comment]
Good spot, i've fixed the default to be 20

**Comment by Stardesign2024** [comment]
> 有同樣的問題。解決方案是將「最大建議」設置從 0 增加。我想這是一個新設置？
> 
> ![image](https://private-user-images.githubusercontent.com/9431420/316811633-13ab9c68-81b0-4c4f-97dd-1a43e77b7ac5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0OTIwMjQsIm5iZiI6MTcxMTQ5MTcyNCwicGF0aCI6Ii85NDMxNDIwLzMxNjgxMTYzMy0xM2FiOWM2OC04MWIwLTRjNGYtOTdkZC0xYTQzZTc3YjdhYzUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjZUMjIyMjA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGQ5OWUxYmM4MzRlMjQ4ODQyYjQ1MzhlMzk1ZmNhOTAzNjM2MjQ2NDc5YTk5OTA4MWRjMTBlOWE0NGQwMTdiMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ruDP4slwaCvEUjTdSXNqbyi519cE1DYHozFmSd1b9ls)

very cool！
