### ISSUE TITLE
Cannot import: unexpected keyword argument 'root_dir'

### ISSUE THREAD

**Issue by mattymatty** [pythongosssss/ComfyUI-Custom-Scripts#22]
File "C:\Users\NAME\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts\__init__.py", line 12, in <module>
    files = glob.glob("*.py", root_dir=py, recursive=False)
TypeError: glob() got an unexpected keyword argument 'root_dir'

Cannot import C:\Users\NAME\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts module for custom nodes: glob() got an unexpected keyword argument 'root_dir'

**Comment by pythongosssss** [comment]
Looks like you're probably running a version of python pre 3.10 as that is when that parameter was added, if you try updating your python to 3.10 and see if that resolves it
