### ISSUE TITLE
Missing menus

### ISSUE THREAD

**Issue by Phando** [pythongosssss/ComfyUI-Custom-Scripts#23]
Thank you for the extended functionality. My menus got mucked up when using your custom node. It only lets you view one level of menu at a time. In the chrome console I see the following error. 

`parentMenu must be of class ContextMenu, ignoring it.`

https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/215984/1ca8afd0-6df1-4f68-9703-49f93d62cccb

**Comment by pythongosssss** [comment]
This should now be fixed

**Comment by Phando** [comment]
@pythongosssss Totally fixed, thank you! No I need to learn all your nodes...
