### ISSUE TITLE
How to hide the image feed icon?

### ISSUE THREAD

**Issue by Aljnk** [pythongosssss/ComfyUI-Custom-Scripts#230]
Hi. I want to hide (disable) the image feed icon - how can I do this?

![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/11256478/d08859e5-1cd0-43a4-b5b3-cfbccf1cc9f0)

**Comment by pythongosssss** [comment]
You can now select "hidden" as an option in the settings
