### ISSUE TITLE
Conflicts with the latest version of COMFYUI, unable to open the right-click input node menu.

### ISSUE THREAD

**Issue by msola-ht** [pythongosssss/ComfyUI-Custom-Scripts#234]
![20240413_170201_861_copy](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/45963567/8e046aa4-13ca-4846-bb88-74f0c3dc3c24)

**Comment by freemantc9527** [comment]
Same question!

**Comment by msola-ht** [comment]
It's a localization issue that has been updated and resolved.
