### ISSUE TITLE
(FR) Please add the ability to use "view info" for Lora's in ComfyRoll Lora Stack

### ISSUE THREAD

**Issue by SeditiousSov** [pythongosssss/ComfyUI-Custom-Scripts#235]
The ability to view Lora Information for trigger words is absolutely amazing, but it only works with the built-in load lora node.  Please add the ability to view info on stacked Loras like ComfyRoll's Lora Stacker.

**Comment by richkel** [comment]
I like this idea of a lora stack the view info is a wonderful feature

**Comment by pythongosssss** [comment]
![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/125205205/7de78905-9df1-4d4c-8f89-bb5265b516fa)
You should be able to use this setting to enter the names of lora widgets

**Comment by richkel** [comment]
> ![image](https://private-user-images.githubusercontent.com/125205205/331496346-7de78905-9df1-4d4c-8f89-bb5265b516fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwNjU3MzAsIm5iZiI6MTcxNjA2NTQzMCwicGF0aCI6Ii8xMjUyMDUyMDUvMzMxNDk2MzQ2LTdkZTc4OTA1LTlkZjEtNGQ0Yy04Zjg5LWJiNTI2NWI1MTZmYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxOFQyMDUwMzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZjA4NmUzNDgyYjg0NjdmMWY4NDZjYTY5MzcxM2JkNjgwMmNhMWNlMWVjNmVkMmNhMWI5Zjg5NjMyYzA0MzY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.K8M1_4OIj3DkvyH5VPd8LthfRZ3q3lVatkC61KFdCxM) You should be able to use this setting to enter the names of lora widget

I didn't realize this was an option im sorry. I am confused on what information I need to use to get the Lora stacker from efficiency-nodes-comfyui to show the lora info and checkpoint info, would you be willing to give me an example?

**Comment by pythongosssss** [comment]
The name of the node followed by the widget, so for the standard lora loder:
`LoraLoader.lora_name`

**Comment by pythongosssss** [comment]
I've added support for using regex in the widget name, so you can use
Lora Stacker.lora_name_.*
