### ISSUE TITLE
Square root

### ISSUE THREAD

**Issue by StefanoBalocco** [pythongosssss/ComfyUI-Custom-Scripts#238]
Hello!
Would be very useful, in the math node, a square root function.

For example if I want to calculate the width for a specific ratio and pixel count(1920x1080, in the example), I need to calculate:
sqrt(ratio.width*(1920*1080)/ratio.height)

Is possible to implement that function?

Thanks!

**Comment by pythongosssss** [comment]
Added sqrt!
