### ISSUE TITLE
Cannot read properties of undefined (reading 'inputs')

### ISSUE THREAD

**Issue by yincangshiwei** [pythongosssss/ComfyUI-Custom-Scripts#239]
I am using the latest version of ComfyUI. After installing ComfyUI Custom Scripts, I am unable to select display nodes when using text to input.

ComfyUI: 2140[4ee9aa](2024-04-21)
![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/8185843/979e831d-a30f-426c-b1c9-2d89af440567)
![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/8185843/1a1bf67d-043a-4c7f-94dd-0fb08b264c98)

**Comment by pythongosssss** [comment]
If you click on main.js what file is that

**Comment by pythongosssss** [comment]
No update
