### ISSUE TITLE
Repeatedly clicking "Go to node" opens duplicate menus

### ISSUE THREAD

**Issue by arcusmaximus** [pythongosssss/ComfyUI-Custom-Scripts#24]
A quite simple one: each time you click "Go to node" in the context menu, an additional node type menu pops up (the previous one isn't closed). Similarly, each time you click a node type, an additional node list pops up, again without closing the previous one.

**Comment by pythongosssss** [comment]
This may have been due to the same issue as #23, I can't recreate on the latest updates, if you could try updating to see if that resolves it

**Comment by arcusmaximus** [comment]
Yes, the new version fixes it. Thank you!
