### ISSUE TITLE
QoL features request: Scroll to browse through images, gallery should update as new images generate

### ISSUE THREAD

**Issue by Yasand123** [pythongosssss/ComfyUI-Custom-Scripts#241]
I've found these scripts incredibly helpful they've already saved me a significant amount of time. Thankyou to the developer and contributors.

I think some very minor changes could also enhance the overall polish.

1. Being able to to navigate through opened images using the scroll wheel (as opposed to using the arrows on the keyboard) on their mouse, akin to functionality found in some image viewers.
2. While viewing an image, newer images generated as I browse are not automatically included in the current "session." Updating the image list requires closing and reopening an image.

**Comment by pythongosssss** [comment]
Thanks for adding those @DrJKL !
