### ISSUE TITLE
[Feature] Support "preview.jpeg" format

### ISSUE THREAD

**Issue by sumback** [pythongosssss/ComfyUI-Custom-Scripts#244]
Hello, 

First of all let me thank you for these fantastic custom_nodes.

I would like to ask to add the `preview.jpeg` format on
https://github.com/pythongosssss/ComfyUI-Custom-Scripts/blob/3f2c021e50be2fed3c9d1552ee8dcaae06ad1fe5/py/better_combos.py#L88

In order to display previews download by https://github.com/LykosAI/StabilityMatrix

Could you please think about it? 
THANKS.

**Comment by pythongosssss** [comment]
Done!
