### ISSUE TITLE
Can no longer Right-Click as of f819039

### ISSUE THREAD

**Issue by Lightsockie** [pythongosssss/ComfyUI-Custom-Scripts#25]
Last working commit: https://github.com/pythongosssss/ComfyUI-Custom-Scripts/commit/f6c29acbc7526eb92c60a73c2fc52da51426c233

ComfyUI version `95d796fc85608272a9bf06a8c6c1f45912179118`
Python `3.11.3`

Just walked down the tree, and as of https://github.com/pythongosssss/ComfyUI-Custom-Scripts/commit/f81903994288a9d9d74f1ff8258d11881311ee27 I stopped being able to right click (confirmed on two different workstations/browsers).

I'm guessing it has something to do with that slick new `js/contextMenuHook.js`, but can't say for sure. Nothing showing up in the logs, so not sure what all I can provide that's useful. Happy to give more though if you point me in the right direction

On `f819039` it is working, technically, but an odd quirk now is that when you go down a menu, you have to click it (hovering won't spawn the submenu), and when you click it it kills the old menu and spawns the submenu in it's place

**Comment by pythongosssss** [comment]
Hmm, I'm not having any issues with the context menus in any browser i've tested (on Windows)
What OS and browsers have you tried?
If you look in the browser dev tools console (F12 or CTRL+SHIFT+i in most browsers) do you get any errors either on start or on right clicking?
Is right click working anywhere? 
Do combo list dropdowns work? (e.g. checkpoint loader or lora loader)

**Comment by pythongosssss** [comment]
Another user had the same issue, it was that the scripts dont load in a deterministic order, and the lora scripts rely on the context menu hook being loaded first. 
This should now be fixed

**Comment by Lightsockie** [comment]
Yep, pulled in the newest commits and it's working again. Thanks @pythongosssss
