### ISSUE TITLE
Missing preset text message locking comfyUI indefinitely

### ISSUE THREAD

**Issue by tarkansarim** [pythongosssss/ComfyUI-Custom-Scripts#253]
When I load a workflow through a different comfyui that runs through a different port and open a workflow that has a "preset text" node, I get an error message that says that the preset it's trying to load is missing and when I confirm the message a new one pops right after and stays in an infinite loop locking down my ComfyUI for this port indefinitely.

**Comment by jamesdouma** [comment]
I have the same issue

**Comment by pythongosssss** [comment]
I think you have another custom script doing something odd, possibly calling the graph to prompt function continually?
I've updated this to not show an alert but instead highlight the node as a quick workaround.
