### ISSUE TITLE
[Feature request] set name workflow when onLoad()

### ISSUE THREAD

**Issue by pvp-by** [pythongosssss/ComfyUI-Custom-Scripts#26]
you have made great additions (icon, queue) export to png, maybe this issue will be somewhere near what you have already researched ? [[Feature request] Keeping the loaded workflow's filename visible. #983](https://github.com/comfyanonymous/ComfyUI/issues/983).

**Comment by pythongosssss** [comment]
I've take a look, and its not possible to set the name from an extension without replacing the button click as the "workflow.json" is hardcoded.
I have however updated my workflows script to use the last used name, but you need to use the submenu to save it
![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/125205205/83ed8c0a-0de5-4f73-94a3-f6a84f5a6b76)
