### ISSUE TITLE
ImportError: Using `low_cpu_mem_usage=True` or a `device_map` requires Accelerate: `pip install accelerate`

### ISSUE THREAD

**Issue by 99xmx** [pythongosssss/ComfyUI-Custom-Scripts#262]
![1716994174799](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/171140102/1bc1adb0-b2c0-4d1c-a9fa-db299a52199a)
更新了transformers 也不行。。。

**Comment by pythongosssss** [comment]
This looks to be an error with the SVD nodes you are using if you can please open an issue there
