### ISSUE TITLE
save workflow default to last saved file

### ISSUE THREAD

**Issue by RichardLuo0** [pythongosssss/ComfyUI-Custom-Scripts#272]
For now, the `save to workflow` button will ask for a name every time. Though it will auto-populate the text field if saved before, it is really inconvenient to type it every time.
I suggest remembering the last saved file path. `ctrl+s` should save to that file automatically. Also, add another option like `save to <the last saved file>` to the save drop-down menu.

**Comment by pythongosssss** [comment]
This feature is now deprecated due to the core comfyui workflow management
