### ISSUE TITLE
Locked node icon position is wrong when node is collapsed

### ISSUE THREAD

**Issue by Dimitro** [pythongosssss/ComfyUI-Custom-Scripts#273]
Node isn't collapsed:
![4gw2Be1eyR](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/833418/89706cac-5156-4ca7-ae4e-27502ba1553b)

Node collapsed:
![A8seuugslf](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/833418/8b32d2ff-e715-4f23-9e2f-1e4564157220)

**Comment by pythongosssss** [comment]
Fixed!
