### ISSUE TITLE
could you please add a node achive convert hexadecimal color values to hue values？

### ISSUE THREAD

**Issue by hexiaoyu946** [pythongosssss/ComfyUI-Custom-Scripts#276]
Dear developer, I want to convert hexadecimal color values to hue values, please ask if you can add a node to achieve this function, thank you very much
![屏幕截图 2024-06-19 011941](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/72909117/ae0bc769-094e-4f58-b89d-de2c8bf8d4bc)

**Comment by pythongosssss** [comment]
You can engineer one using a few Math Expression nodes, not the simplest but once you've done it once you can convert it to a group node & component using the manager to use in other workflows.

![image](https://github.com/user-attachments/assets/1a2c0ccf-2680-4ca0-a6eb-a2034a907414)

Converting that to a group node and hiding the inner workings
![image](https://github.com/user-attachments/assets/3feccfe3-1c34-4076-a05f-78f5d0c7ca80)

[rgb2hue.json](https://github.com/user-attachments/files/16203613/rgb2hue.json)
