### ISSUE TITLE
ShowText nodes keep growing when bypassed

### ISSUE THREAD

**Issue by alexopus** [pythongosssss/ComfyUI-Custom-Scripts#278]
![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/25933468/92243dcf-c5c1-459c-9c8d-cc1e27b88a03)

I am not sure when it grows exactly. Possibly on page reload or on workflow reload.
But not on every workflow execution.

I have multiple of them and they seem to grow at the same rate/time.

I can fix it by disabling the bypass and then they will return to normal size on workflow execution.

**Comment by karl-von-knecht** [comment]
I second this. I get this a lot because I use rgthree's Fast Groups Muter.

**Comment by pythongosssss** [comment]
This should now be fixed, please re-open if it isnt!

**Comment by alexopus** [comment]
This is now happening again. Except it also grows if not bypassed.
