### ISSUE TITLE
[FR]: checkpoint subfolders

### ISSUE THREAD

**Issue by DrJKL** [pythongosssss/ComfyUI-Custom-Scripts#28]
Basically the loraSubfolders, but also for checkpoints.

**Comment by pythongosssss** [comment]
Refactoring the submenu stuff at the moment, should hopefulyl be done in a couple of days

**Comment by pythongosssss** [comment]
Progress
![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/125205205/94e00f2f-1aae-4749-a1a6-6e9bbea07e19)

**Comment by DrJKL** [comment]
That's going to be so much nicer

**Comment by pythongosssss** [comment]
This is now available, sorry for the delay had to rework it a few times...!
https://github.com/pythongosssss/ComfyUI-Custom-Scripts#testing-better-loader-lists
