### ISSUE TITLE
show text node get error， text cannot show out

### ISSUE THREAD

**Issue by onestepmumu** [pythongosssss/ComfyUI-Custom-Scripts#281]
Hi, I copy codes in show_text.py to my custom_nodes, but show_text node in my custom_nodes can not show text out, can anyone told me what happen? as image show, the show text node without green snake have same code with ComfyUI-Custom-Scripts/py/show_text.py but text doesn't show out！
![屏幕截图 2024-06-28 001551](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/168327825/3dc3add9-d943-4e07-b185-c2a6e01d8fe9)

**Comment by Yanquansu** [comment]
could you please share the solution of the this problems ?
