### ISSUE TITLE
Image Feed Location left or right with New menu and workflow management cover screen

### ISSUE THREAD

**Issue by xueqing0622** [pythongosssss/ComfyUI-Custom-Scripts#284]
Image Feed Location left or right with New menu and workflow management cover screen like that.
![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/114840118/7b20a661-9099-4ecc-bfd3-dedcd3aa19a8)
also the image feed text no auto hide when the mouse no on it  like before
hope will fixed quickly

**Comment by Troyificus** [comment]
Having a similar issue, except my entire workspace is covered and unusable. Removing this custom node fixes the issue.

![i7bxkkbq4rad1](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/39455501/83e9931a-c814-4092-96aa-b1d144e3ffd2)

**Comment by pythongosssss** [comment]
This should be resolved by this PR
https://github.com/comfyanonymous/ComfyUI/pull/3909

**Comment by xueqing0622** [comment]
still same
![image](https://github.com/user-attachments/assets/db9be41e-dfb3-4bab-9968-30a847bde74e)
![image](https://github.com/user-attachments/assets/985f89eb-2117-480b-902d-1725d16bc30f)

**Comment by pythongosssss** [comment]
Did you test using the PR in the comfyui repo (that is now merged, so if you update ComfyUI it should apply)

**Comment by JorgeR81** [comment]
It's fixed for me now. 
It also works perfectly with the rgthree progress bar.

![feed](https://github.com/user-attachments/assets/d5f0d032-95ed-4c7a-b0b8-8acd7f78e1d6)

**Comment by xueqing0622** [comment]
yes, it fixed now! thx!
