### ISSUE TITLE
Add Support for Wildcard Characters for "View Lora info..."

### ISSUE THREAD

**Issue by Rubecks** [pythongosssss/ComfyUI-Custom-Scripts#285]
I am requesting the addition of wildcard character support for the string that defines which nodes should have the "View Lora info..." option available, the "Model Info - Lora Nodes/Widgets" option in the settings screen.

It would be particularly useful for nodes such as the LoRA Stacker from Efficiency Nodes, that include widgets with names like LoRA Stacker.lora_name_1 to LoRA Stacker.lora_name_99. In order to make the "View Lora info..." option available for all these widgets, one has to explicitly define each node individually. 

Example:
Instead of listing each widget individually like this:

```
LoRA Stacker.lora_name_1
LoRA Stacker.lora_name_2
...
LoRA Stacker.lora_name_99
```

One could use a wildcard character to achieve the same result:

```
LoRA Stacker.lora_name_*
```

Sure, nobody uses 99 Loras, I just defined 9 widgets, but it isn't an elegant solution either, and the string could get pretty long with the time.
Thank you for considering this request.

**Comment by pythongosssss** [comment]
I've added support for using regex in the widget name, so you can use
`Lora Stacker.lora_name_.*`
