### ISSUE TITLE
Changed - remaining issue is image feed continues to pop up, Favicons don't show on browser

### ISSUE THREAD

**Issue by EricRollei** [pythongosssss/ComfyUI-Custom-Scripts#29]
Hello, I just updated the ComfyUI-Custom-Scripts yesterday.  I noticed that I no longer have the favicon showing on the browser tab and my preferences for node wiring is not being saved.  Also my image feed has only white rectangles for the left and right toggles where I believe this used to be white arrows.   I would like a way to turn off the image feed altogether as while I do use other features, I find the ImageFeed unneeded.

**Comment by DrJKL** [comment]
There should be a close button on the image feed: 
![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/448862/83a531d5-c297-4222-bba5-20fcb21a7857)

**Comment by EricRollei** [comment]
Yes, but it always appears again. And also new pages start with it. It used to be different before the last update. There are several things wrong. The little icon at the tab, the not remembering the preferences. And not being able to stop the feed from appearing are three that I know of

**Comment by pythongosssss** [comment]
Are you getting any errors in the browser console (F12 or ctrl+shift+i on most browsers)
The state of the image feed should be saved each time you open/close it, however your one is clearly having some issues, hopefully there will be a useful error in the console for me to take a look at!

**Comment by pythongosssss** [comment]
Do you have https://github.com/melMass/comfy_mtb installed? This has a fork of the image feed that doesnt support toggling, my one should save the state of the image feed

**Comment by EricRollei** [comment]
Yes, it turns out I have both MTB and tiny terra nodes installed.   Reading through the other issue posts, I see that both sets conflict with yours.   I'm not sure how to resolve since I don't really want to remove any entire set.   Is there a way to remove or deactivate some of yours?  In particular, I'd like to turn off the link render styles, or set it to spline, and just delete the image feed.  btw - when I have image feed open and que up a bunch of gens, I'll get an OOM in the browser and the tab with comfy will fail to load.   So I definitely need to deactivate the image feed.   I read one of the other issue threads someone deleted the script but got errors so I'm not sure what's the best way to do this?

**Comment by pythongosssss** [comment]
You need to set the link render styles using the other extension, my one defaults to spline so it will be due to the other other script setting it to something else.

Try removing the image feed from MTB, then close mine using the [X] button (ive just done an update that will reduce memory use when it's closed)

**Comment by EricRollei** [comment]
I disable the ttn section that was causing the conflict with yours, however, I can't see how to remove the image feed from MTB and it's not clear since I've not ever seen an image feed from MTB other than for videos but that fed is in its own box, not floating.  I'm not currently using any MTB nodes, but somehow your image feed continues to pop up. I hit the X and/or clear before but it still pops up.  It's maddening. I don't want a feed as I use other tools for that.   Telling me to go disable some other set of nodes is missing the point.  I'd like to know how to disable your image feed, please.

**Comment by pythongosssss** [comment]
Can you please show a screenshot/video

**Comment by EricRollei** [comment]
What do you want to see?  I'm going to ask one more time. Please tell me how to disable the image feed portion of your scripts. It pops up every time I generate an image even after closing it.  If you won't tell me how to disable that, then forget it man, I'll just delete your whole node folder and move on.

**Comment by EricRollei** [comment]
![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/97568200/242773c7-5e55-442e-9370-a3e3f2e962ad)

**Comment by EricRollei** [comment]
I guess you didn't believe me? It literally pops up every time.  I hit the X button and it goes away, but if I load another comfy window or a new workflow it will come back up. Sometimes it comes back up on the next gen.   I really dislike the image feed and have asked you many times now to tell me how to disable it.   Can I just delete the .py file for image feed?    I do not want the image feed at all.  It also causes OOM errors with high batch numbers.

**Comment by EricRollei** [comment]
![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/97568200/153712ae-61a9-4520-82d8-cdf0ce2a2b74)
Here you can see the favicon is not showing on the tab.

**Comment by pythongosssss** [comment]
> I guess you didn't believe me? It literally pops up every time. I hit the X button and it goes away, but if I load another comfy window or a new workflow it will come back up. Sometimes it comes back up on the next gen. I really dislike the image feed and have asked you many times now to tell me how to disable it. Can I just delete the .py file for image feed? I do not want the image feed at all. It also causes OOM errors with high batch numbers.

Correct, this is not my image feed, this is from here:
https://github.com/melMass/comfy_mtb
https://github.com/melMass/comfy_mtb/blob/main/web/imageFeed.js

My image feed does not have "Load Session History"

**Comment by pythongosssss** [comment]
Mine already saves the closed state, so once you closed it, if you refresh it wont open again until you click the little picture icon.
That icon is in both scripts so I cant say which that specific one is from in the image.

You can tell if it is my feed if it has a resize feed menu
![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/125205205/53cf1e7e-1400-4b7a-9800-b6b6d04ae858)

For the favicon, does it show after you queue a prompt? And does the title of the tab update e.g.
![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/125205205/96449a8d-60a7-49c8-b68b-13b6eca32f26)
