### ISSUE TITLE
向节点和组添加自定义颜色选择器-为什么我的不显示

### ISSUE THREAD

**Issue by BannyLon** [pythongosssss/ComfyUI-Custom-Scripts#295]
我安装了ComfyUI-Custom-Scripts插件，在使用节点颜色功能时，没有自定义颜色这一项，好像之前是有的，升级之后就没有了。不知道问题出在哪？

![1721197970253](https://github.com/user-attachments/assets/e6df854c-3ddc-4843-a1a6-2d941d0e0a6a)

**Comment by BannyLon** [comment]
我知道了，是因为汉化的原因。

**Comment by Pythonpa** [comment]
修好了吗？这个作者貌似挺忙，最近这个项目都没啥更新了，和汉化插件那边沟通了（https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/issues/254#issuecomment-2252010011），不是他们那边的原因

**Comment by BannyLon** [comment]
大赞，感谢！已经能用了！
