### ISSUE TITLE
Link Render Mode locked to STRAIGHT and won't save SPLINE preferences

### ISSUE THREAD

**Issue by rethink-studios** [pythongosssss/ComfyUI-Custom-Scripts#30]
Hey hey!
Updated to your latest a couple days ago, and currently, can not get SPLINE saved as my default.

link:
https://www.dropbox.com/s/b3jnaj82lsw8i7y/Pythongosssss_Link_Render_Mode_02.mp4?dl=0

**Comment by pythongosssss** [comment]
Are you getting any errors in the browser console (F12 or ctrl+shift+i on most browsers) either on startup or when changing/saving the setting?

**Comment by rethink-studios** [comment]
Here's the log:

I haven't gotten MTB Roop working just yet, and that's the error below..

D:\ComfyUI>.\python_embeded\python.exe -s ComfyUI\main.py  --preview-method auto --windows-standalone-build

Prestartup times for custom nodes:
   0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 24564 MB, total RAM 130813 MB
xformers version: 0.0.20
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
Using xformers cross attention
Adding extra search path checkpoints D:/stable-diffusion-webui\models/Stable-diffusion
Adding extra search path configs D:/stable-diffusion-webui\models/Stable-diffusion
Adding extra search path vae D:/stable-diffusion-webui\models/VAE
Adding extra search path loras D:/stable-diffusion-webui\models/Lora
Adding extra search path upscale_models D:/stable-diffusion-webui\models/ESRGAN
Adding extra search path upscale_models D:/stable-diffusion-webui\models/SwinIR
Adding extra search path upscale_models D:/stable-diffusion-webui\models/RealESRGAN
Adding extra search path upscale_models D:/stable-diffusion-webui\models/GFPGAN
Adding extra search path embeddings D:/stable-diffusion-webui\embeddings
Adding extra search path hypernetworks D:/stable-diffusion-webui\models/hypernetworks
Adding extra search path controlnet D:/stable-diffusion-webui\extensions/sd-webui-controlnet/models
Adding extra search path sam D:/stable-diffusion-webui\models/sam
### Loading: ComfyUI-Impact-Pack (V3.4)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.2)
### Loading: ComfyUI-Manager (V0.17)
### ComfyUI Revision: 1233 [834ab278]
Failed to auto update `Quality of Life Suit`
QualityOfLifeSuit_Omar92_DIR: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-QualityOfLifeSuit_Omar92
Imported node: DT_Flatten_Colors
Imported node: DT_FontText
Imported node: DT_GenerateNoise
Imported node: DT_Glitch_This
Imported node: DT_Hue_Rotation
Imported node: DT_Load_Picture_Index
Imported node: DT_PILGram
Imported node: DT_Pixel_Sort
Imported node: DT_Play_Sound_At_Execution
Imported node: DT_PromptGen
Imported node: DT_Solid_Color
Imported node: DT_Swap_Color_Mode
Imported node: DT_Flatten_Colors
Imported node: DT_FontText
Imported node: DT_GenerateNoise
Imported node: DT_Glitch_This
Imported node: DT_Hue_Rotation
Imported node: DT_Load_Picture_Index
Imported node: DT_PILGram
Imported node: DT_Pixel_Sort
Imported node: DT_Play_Sound_At_Execution
Imported node: DT_PromptGen
Imported node: DT_Solid_Color
Imported node: DT_Swap_Color_Mode
### Loading: ComfyUI-Workflow-Component (V0.39.5) !! WARN: This is an experimental extension. Extremely unstable. !!
Comfyroll Custom Nodes: Loaded
Davemane42 Custom Nodes: Loaded
[tinyterraNodes] Loaded
Log level: 20
[comfy_mtb] | WARNING -> cv2.ximgproc.guidedFilter not found, use opencv-contrib-python
[comfy_mtb] | ERROR -> Some nodes failed to load:
        Failed to import faceenhance because ModuleNotFoundError: No module named 'basicsr'
        Failed to import faceswap because ModuleNotFoundError: No module named 'insightface'
        Failed to import fun because ModuleNotFoundError: No module named 'qrcode'
        Failed to import image_interpolation because ModuleNotFoundError: No module named 'tensorflow'

Check that you properly installed the dependencies.
If you think this is a bug, please report it on the github page (https://github.com/melMass/comfy_mtb/issues)
[comfy_mtb] | INFO -> Loaded the following nodes:
        Smart Step (mtb): Utils to control the steps start/stop of the KAdvancedSampler in percentage
        Text To Image (mtb): Utils to convert text to image using a font
        Styles Loader (mtb): Load csv files and populate a dropdown from the rows (à la A111)
        B Box From Mask (mtb): From a mask extract the bounding box
        Bounding Box (mtb): The bounding box (BBOX) custom type used by other nodes
        Crop (mtb): Crops an image and an optional mask to a given bounding box
        Uncrop (mtb): Uncrops an image to a given bounding box
        Deep Bump (mtb): Normal & height maps generation from single pictures
        Save Tensors (mtb): Debug node that will probably be removed in the future
        Color Correct (mtb): Various color correction methods
        Hsv To Rgb (mtb): Convert HSV image to RGB
        Rgb To Hsv (mtb): Convert RGB image to HSV
        Image Compare (mtb): Compare two images and return a difference image
        Denoise (mtb): Denoise an image using total variation minimization.
        Blur (mtb): Blur an image using a Gaussian filter.
        Deglaze Image (mtb): Remove adversarial noise from images
        Mask To Image (mtb): Converts a mask (alpha) to an RGB image with a color and background
        Colored Image (mtb): Constant color image of given size
        Image Premultiply (mtb): Premultiply image with mask
        Image Resize Factor (mtb): Extracted mostly from WAS Node Suite, with a few edits (most notably multiple image support) and less features.
        Save Image Grid (mtb): Save all the images in the input batch as a grid of images.
        Latent Lerp (mtb): Linear interpolation (blend) between two latent vectors
        Image Remove Background Rembg (mtb): -
        Int To Number (mtb): Node addon for the WAS Suite. Converts a "comfy" INT to a NUMBER.
        Load Image Sequence (mtb): Load an image sequence from a folder. The current frame is used to determine which image to load.
        Save Image Sequence (mtb): Save an image sequence to a folder. The current frame is used to determine which image to save.
Total VRAM 24564 MB, total RAM 130813 MB
xformers version: 0.0.20
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
WAS Node Suite: BlenderNeko's Advanced CLIP Text Encode found, attempting to enable `CLIPTextEncode` support.
WAS Node Suite: `CLIPTextEncode (BlenderNeko Advanced + NSP)` node enabled under `WAS Suite/Conditioning` menu.
WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `D:\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 190 nodes successfully.

        "Success is not just about making money. It's about making a difference." - Unknown


Import times for custom nodes:
   0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\SDXLAspectRatio.py
   0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\sampler_tonemap.py
   0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\sampler_rescalecfg.py
   0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\Textnode.py
   0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\advanced_model_merging.py
   0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_Noise
   0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_ADV_CLIP_emb
   0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_TiledKSampler
   0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_SeeCoder
   0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_Dave_CustomNode
   0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-QualityOfLifeSuit_Omar92
   0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\comfyui-animatediff
   0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\images-grid-comfy-plugin
   0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
   0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Workflow-Component
   0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger
   0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\comfy_mtb
   0.2 seconds: D:\ComfyUI\ComfyUI\custom_nodes\clipseg.py
   0.2 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager
   0.3 seconds: D:\ComfyUI\ComfyUI\custom_nodes\comfy_controlnet_preprocessors
   0.4 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes
   0.4 seconds: D:\ComfyUI\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.5 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   0.6 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Vextra-Nodes
   0.8 seconds: D:\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui

Starting server

To see the GUI go to: http://127.0.0.1:8188
QualityOfLifeSuit_Omar92::NSP ready

**Comment by pythongosssss** [comment]
Ah, thats the output from your ComfyUI console rather than from your browser
Here is how to open the browser console in Chrome:
https://support.google.com/docs/thread/1873663/collecting-console-logs-chrome-browser-only?hl=en

**Comment by rethink-studios** [comment]
Gotchu!

This is what I see in the console:


![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/60104539/019e21d4-53c2-4f65-b1a1-4a3ff08a472e)


![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/60104539/4709b5c7-577a-48af-b1ca-6154671ada40)

**Comment by Aunalise** [comment]
I have the same issue, and I don't get any error messages in the console throughout the process of changing the links/wires to 'spline' or any other type, nor during the load of a new workspace (which defaults back to 'straight).'

**Comment by za-wa-n-go** [comment]
I have the same symptoms.

**Comment by pythongosssss** [comment]
Looks like this will almost certainly be due to another extension setting the value to something else, the default I have set is spline

Form a quick search looks like: https://github.com/TinyTerra/ComfyUI_tinyterraNodes/tree/main 
Has its own system for changing the link render mode via right click on the canvas, and their default is straight.

There may be other custom nodes that also change it

**Comment by Aunalise** [comment]
I uninstalled tinyTerraNodes and I still get the links reverting to 'straight.' 

I had uninstalled tinyTerraNodes and anything else reporting an issue of loading in the Import times for custom nodes list, which included ComfyUI_Custom-Scripts.
Then after restart there were no reported import issues.
Then I re-installed Custom-Scripts only.
No reported import issue after that.
But the links revert to 'straight,' now.

**Comment by rethink-studios** [comment]
Same here, as of this morning.

**Comment by pythongosssss** [comment]
Can you please try changing the value using the tinyTerraNodes option, another user on the Comfy element channel has confirmed their issue was due to that overriding my setting
![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/125205205/44922192-9a6f-4662-a856-d10f475ab94f)

**Comment by Aunalise** [comment]
tinyTerraNodes overrides the settings of the Pythongosssss Custom-Scripts extension.
It defaults to 'straight,' not 'spline' probably due to uninitialized value of '0' equalling 'straight' links.
This can be set permanently to 'spline' by going to a node, and right-clicking right on a node-link dot.
Select Link Style (ttN) and then 'Spline'
The links will update to the chosen style upon the first click on the workspace.

See below:
![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/135768889/b1a81a1d-dc84-4a56-9362-9d1a4d65a883)

**Comment by hobojoker** [comment]
> tinyTerraNodes overrides the settings of the Pythongosssss Custom-Scripts extension. It defaults to 'straight,' not 'spline' probably due to uninitialized value of '0' equalling 'straight' links. This can be set permanently to 'spline' by going to a node, and right-clicking right on a node-link dot. Select Link Style (ttN) and then 'Spline' The links will update to the chosen style upon the first click on the workspace.
> 
> See below: ![image](https://user-images.githubusercontent.com/135768889/257934354-b1a81a1d-dc84-4a56-9362-9d1a4d65a883.png)

This fixed it for me too! Hopefully this concludes the issue for everyone

**Comment by rethink-studios** [comment]
Thumbs!
Thanks for the screenshot, as well. I had no idea! :)

Closing...
