### ISSUE TITLE
(simple) FEATURE REQUEST: Toggle Image Feed - do not want

### ISSUE THREAD

**Issue by Duemellon** [pythongosssss/ComfyUI-Custom-Scripts#31]
I do not want the Image Feed but I want everything else. How can I toggle/remove just that?

Heck, or pick & choose any of the particulars if I didn't want them? I renamed the js for Image Feed to have .old but it still loaded & ComfyUI just gave me so many errors (of course.

I hope this is a simple thing

**Comment by pythongosssss** [comment]
Do you have https://github.com/melMass/comfy_mtb installed? This has a fork of the image feed that doesnt support toggling, my one should save the state of the image feed

**Comment by pythongosssss** [comment]
Have you removed the image feed from comfy_mtb and it still shows?
My feed saves the state, so if you close it, it wont open again until you re-open the feed, his fork doesnt have that feature.

For the spline defaulting, my script defaults to spline. I imagine you have another extension changing it, see here:
https://github.com/pythongosssss/ComfyUI-Custom-Scripts/issues/30#issuecomment-1661602518

**Comment by Duemellon** [comment]
not sure how to edit script to do so. Also, I don't want the image tab gone forever, I just want to toggle here & there.
