### ISSUE TITLE
Feature request: Closing the feed, and limiting max image number

### ISSUE THREAD

**Issue by mi8m** [pythongosssss/ComfyUI-Custom-Scripts#314]
Hey I think those two additions would be very useful, even more for my case as I gen a lot of small stuff in batches (QR Codes), and they keep stealing more and more ram in to keep the feed (I've reached 2 gigs on it alone). Something like a 10 image limit would keep the feed useful while avoiding the problem.

**Comment by pythongosssss** [comment]
You can close the feed with the X button:
![image](https://github.com/user-attachments/assets/2998c5fb-f309-4340-9313-f6ed36538cfc)

To fully disable set the "Image feed location" setting to hidden

I've added a new setting for the max number of images to keep in the feed:
![image](https://github.com/user-attachments/assets/4ae4191b-6e57-42fe-aaa2-b53e8e7ff29a)

**Comment by mi8m** [comment]
Oh thx I guess I need to pull
