### ISSUE TITLE
ComfyUI update breakes all math nodes.

### ISSUE THREAD

**Issue by 49RpK5dY** [pythongosssss/ComfyUI-Custom-Scripts#315]
This [Execution Model Inversion](https://github.com/comfyanonymous/ComfyUI/commit/5cfe38f41c7091b0fd954877d9d7427a8b438b1a) seriously breaks some things.
Any chance to get a quick fix or there needs to be a major rewrite of the code?
![20240815_1852 ss](https://github.com/user-attachments/assets/768b9ac9-4d2d-4e0a-b8a4-77dc2044ed4c)

**Comment by memedoggo** [comment]
+1 
it broke my workflow as well...

**Comment by enternalsaga** [comment]
+1

**Comment by Neytiri7** [comment]
+1

**Comment by pythongosssss** [comment]
I've done a workaround for this issue if you could please see if it resolves the issue for you
https://github.com/pythongosssss/ComfyUI-Custom-Scripts/commit/a19d0cc4adc4f746862a3f0051dca4931d0e40da

**Comment by memedoggo** [comment]
@pythongosssss 
working now, thanks!

**Comment by 49RpK5dY** [comment]
Yes. It's working now. Thanks.
