### ISSUE TITLE
[BUG] Clicking outside the image now opens the image instead of closing the lightbox

### ISSUE THREAD

**Issue by DrJKL** [pythongosssss/ComfyUI-Custom-Scripts#316]
https://github.com/pythongosssss/ComfyUI-Custom-Scripts/commit/fd4fa5c4ce87436846e4805cc7c99b84a044c3a3#commitcomment-145381848

**Comment by DrJKL** [comment]
@wouterdebie

**Comment by pythongosssss** [comment]
Mergd your fix, ty.
