### ISSUE TITLE
Feature request: Snap nodes to grid

### ISSUE THREAD

**Issue by andreszs** [pythongosssss/ComfyUI-Custom-Scripts#32]
Currently, to snap nodes to grid the user must hold down <kbd>Shift</kbd>, which is simply idiotic because of course I would have to glue the <kbd>Shift</kbd>key while using Comfy.... I like to have my nodes properly aligned for better display, if this plugin could add this option to snap nodes without <kbd>Shift</kbd>, **that would be great**.

**Comment by pythongosssss** [comment]
![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/125205205/294f8d9e-d55d-4cc3-bb69-1d6f1a8718ce)

**Comment by andreszs** [comment]
Thanks!! I'm already using it, just one more detail if possible: **Resizing** a node still requires <kbd>Shift</kbd> to size it in grid-aligned values, this setting should also emulate that keypress on resize events.

**Comment by pythongosssss** [comment]
That should now align on resize too
