### ISSUE TITLE
[PlaySound] WARNING: PlaySound.IS_CHANGED() missing 1 required positional argument: 'self'

### ISSUE THREAD

**Issue by brknsoul** [pythongosssss/ComfyUI-Custom-Scripts#328]
I keep getting this Warning and no sound plays;
`WARNING: PlaySound.IS_CHANGED() missing 1 required positional argument: 'self'`

**Comment by brknsoul** [comment]
Ok, the Warning doesn't affect playsound, just the hardcoded path does. Closing.

**Comment by Jonseed** [comment]
How did you fix it?

**Comment by brknsoul** [comment]
> How did you fix it?

The mp3 file must be in `custom_nodes\ComfyUI-Custom-Scripts\web\js\assets`.

**Comment by Jonseed** [comment]
hmmm, the mp3 is in that folder, and I see the warning, and it doesn't play either.

**Comment by Jonseed** [comment]
I think I just needed to restart Comfy. The sound is working now, but still get the warning.

**Comment by brknsoul** [comment]
> I think I just needed to restart Comfy. The sound is working now, but still get the warning.

The warning's just that, a warning. It doesn't effect the node's operation.
