### ISSUE TITLE
BUG: Image Feed, Firefox won't close Image at X

### ISSUE THREAD

**Issue by Duemellon** [pythongosssss/ComfyUI-Custom-Scripts#33]
After clicking on one of the images in the Image Feed to bring it up I cannot get that new pop-up view to close. The red X in the top right of the canvas/workspace appears but doesn't respond when I click it. 

When I hit the red X for the image feed bar itself the image feed bar does still close however the image remains.

Instead, when I click or drag, the only thing that reacts is the default ComfyUI menu, with the Queue Prompt. ESC does nothing. The buttons on that QP menu don't react. I can still get it to generate a new image with the Ctl+Ent so it's reacting but I can't close the popped-up image.

I can toggle between the images in the Image Feed but the side-arrows are not interactive either.

My pop-up blocker is disabled. Flash is enabled. Latest version of Firefox. 

Thanks for looking into this. I really like the idea of having some sort of image-browsing built into ComfyUI

**Comment by pythongosssss** [comment]
Can you please record a video as I dont think you are talking about my image feed

**Comment by Duemellon** [comment]
Updated to Firefox, not Chrome. I use A1111 in Chrome but FF for ComfyUI

**Comment by Duemellon** [comment]
Trying to get a vid. VidCap is having problems.

**Comment by Duemellon** [comment]
Working on getting a vid

**Comment by pythongosssss** [comment]
That is not my image feed, that is the one from https://github.com/melMass/comfy_mtb

**Comment by Duemellon** [comment]
Cool. I'll hit your other responses in here to see how to disable this one & see what yours does. Thanks!
