### ISSUE TITLE
The Preset Text node cannot load

### ISSUE THREAD

**Issue by wencxxxxxx** [pythongosssss/ComfyUI-Custom-Scripts#331]

**Comment by miurgh** [comment]
same

**Comment by vtn54** [comment]
[This]([Update ComfyUI_frontend to 1.2.40 (](https://github.com/comfyanonymous/ComfyUI/commit/c90459eba0daf15796de2fd7b9e7d8d42f7c7e71)https://github.com/comfyanonymous/ComfyUI/pull/4691[)](https://github.com/comfyanonymous/ComfyUI/commit/c90459eba0daf15796de2fd7b9e7d8d42f7c7e71)) update from Comfyui broke this node.

You Can revert back to previous commits temporarily.

**Comment by miurgh** [comment]
Thank you.
--front-end-version Comfy-Org/ComfyUI_frontend@1.2.2
It worked.

No problems with the following.
--front-end-version Comfy-Org/ComfyUI_legacy_frontend@latest

**Comment by Alleykatz** [comment]
I'm also having this issue

**Comment by Thyrian10** [comment]
Same here, eagerly waiting for a fix...

**Comment by pythongosssss** [comment]
This should be fixed

**Comment by miurgh** [comment]
> Has this problem been solved? 

#469
