### ISSUE TITLE
The workflow turn to mess!!!

### ISSUE THREAD

**Issue by K-O-N-B** [pythongosssss/ComfyUI-Custom-Scripts#337]
please check this issue.

https://github.com/comfyanonymous/ComfyUI/issues/4743

My workflow are mess after upadte comfyui frontend.
The workflow only work fine after disable Custom-Scripts node.

pls fix it.

**Comment by huchenlei** [comment]
The error is caused by core. Not custom node. The fix is available in nightly release 1.2.44. Follow https://github.com/Comfy-Org/ComfyUI_frontend#nightly-release to opt-in nightly release.
