### ISSUE TITLE
Conflicted Nodes (1)  ShowText|pysssss [ComfyUI-Universal-Styler]

### ISSUE THREAD

**Issue by bryanray** [pythongosssss/ComfyUI-Custom-Scripts#338]
【pythongosssss/ComfyUI-Custom-Scripts】Conflicted Nodes (1)

ShowText|pysssss [ComfyUI-Universal-Styler]

**Comment by pythongosssss** [comment]
This is an issue with the other repo copying the node and not giving it a different ID, nothing I can do about it if you could please log an issue there, thanks.
