### ISSUE TITLE
Show Text not showing text

### ISSUE THREAD

**Issue by schoenid** [pythongosssss/ComfyUI-Custom-Scripts#345]
'Show Text' stays empty and does not show any text as expected, while 'Save Text' delivers a text to a file.

So text is supplied to the input, but not displayed.

![image](https://github.com/user-attachments/assets/6e71b32f-4619-40b9-8988-d3371ed3fc52)

Notepad shows, that the text was properly saved to a file.

![image](https://github.com/user-attachments/assets/02456a35-1364-442a-a5d4-5fb45f899f9c)

No errors in the console.

```
** Platform: Windows
** Python version: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
### Loading: ComfyUI-Manager (V2.50.3)
### ComfyUI Revision: 2652 [0c7c98a9] | Released on '2024-09-05'

Torch version: 2.1.2+cu121
```

**Comment by schoenid** [comment]
I've uninstalled all nodes - one node by another ... until I've uninstalled 'DeepFuze'.
Then it was working.

![image](https://github.com/user-attachments/assets/283d4c20-a262-4445-b319-7472ef25073f)

Then I've installed all again, 'DeepFuze" as last.
So with 'DeepFuze' one can switch the display of the shown text on or off !!!

So the problem is there.

**Comment by LinuxWhiz** [comment]
Harley as  And  hi  band  as

**Comment by LinuxWhiz** [comment]
😠

Cody Reichenbach reacted via Gmail
<https://www.google.com/gmail/about/?utm_source=gmail-in-product&utm_medium=et&utm_campaign=emojireactionemail#app>
