### ISSUE TITLE
How to disable the image feed?

### ISSUE THREAD

**Issue by tamal777** [pythongosssss/ComfyUI-Custom-Scripts#35]

**Comment by pythongosssss** [comment]
There is a red X on the feed, next to the clear button, if you click that it will close.

**Comment by pythongosssss** [comment]
https://github.com/pythongosssss/ComfyUI-Custom-Scripts/issues/29#issuecomment-1663737093

**Comment by tamal777** [comment]
> There is a red X on the feed, next to the clear button, if you click that it will close.

oh thank you and thank you for making this scritp.

**Comment by mattymatty** [comment]
How do I get it back after clicking the x?

**Comment by pythongosssss** [comment]
Click the little 🖼️ icon on the menu
![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/125205205/d64df6eb-abde-4914-9451-ded899b4509d)

**Comment by mattymatty** [comment]
Wow that was fast. Thank you!

**Comment by mizukarada** [comment]
There's an issue when it's covered.
<img width="1466" alt="Untitled1" src="https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/111034657/34b4e9eb-c76b-42c6-a264-42326e8d7e75">
That's on MS Edge but when I switch to Safari, that panel is detached and I can see the buttons.

**Comment by MrForExample** [comment]
@pythongosssss @mizukarada 
Same issue on Firefox
