### ISSUE TITLE
ValueError: substring not found

### ISSUE THREAD

**Issue by lesteryebin** [pythongosssss/ComfyUI-Custom-Scripts#352]
Error handling request
Traceback (most recent call last):
  File "E:\ComfyUI\python_embeded\Lib\site-packages\aiohttp\web_protocol.py", line 462, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\python_embeded\Lib\site-packages\aiohttp\web_app.py", line 537, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\python_embeded\Lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI\server.py", line 63, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI\server.py", line 141, in origin_only_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI\server.py", line 75, in cors_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts\py\better_combos.py", line 14, in view
    pos = name.index("/")
          ^^^^^^^^^^^^^^^
ValueError: substring not found

**Comment by siliconx** [comment]
the same issue with u

**Comment by k1064190** [comment]
Me too, I think it's some kinda update issue

**Comment by lesteryebin** [comment]
> #332， 另一个反馈给了解决办法，需要修改3个py文件，我已经把修改好的上传到附件了，然后下载替换对应的旧文件[pyfiles.zip](https://github.com/user-attachments/files/17053747/pyfiles.zip) ![949d84cc54fc294bf4fc25a95856688](https://private-user-images.githubusercontent.com/29881977/368847175-14cf590e-4ebc-4ddb-a9e3-d6ddfde46b31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3MzkyNjUsIm5iZiI6MTcyNjczODk2NSwicGF0aCI6Ii8yOTg4MTk3Ny8zNjg4NDcxNzUtMTRjZjU5MGUtNGViYy00ZGRiLWE5ZTMtZDZkZGZkZTQ2YjMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDA5NDI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0NzAzZThlNTk2NzU5YWM2MTFiZDQ2Y2M0ODdlZjZmMGMwODg0N2YzYWQ1MGVlYWUzN2MwYzdmNDEyMzk0YTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.apCTBvoZWvbZHxeTYZ3uIjgqN-ma6WFtjW2YeUM3vzw) [](https://github.com/user-attachments/files/17053747/pyfiles.zip)

Problem solved, thank you for your reply
