### ISSUE TITLE
Please support preview images in "loraName.preview.png" and "loraName.thumb.jpg" format

### ISSUE THREAD

**Issue by mattymatty** [pythongosssss/ComfyUI-Custom-Scripts#37]
The civitai helper plugin auto downloads lora and checkpoint images in this format. Please support.

loraName.safetensors
loraName.preview.png
loraName.thumb.jpg

**Comment by pythongosssss** [comment]
Which file should be used in preference, preview or thumb?

**Comment by pythongosssss** [comment]
I've taken a look at this: https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper (assuming thats the right one)
I only see it saving a .preview.png, so ive added support for that
Order for checking is: .png, .jpg, .preview.png
