### ISSUE TITLE
Preview Images Are Obscured by the Menu

### ISSUE THREAD

**Issue by EricZhou05** [pythongosssss/ComfyUI-Custom-Scripts#376]
After the ComfyUI update, the preview images of the Image Feed feature are obscured by the menu.

Old：
![PixPin_2024-10-22_23-11-39](https://github.com/user-attachments/assets/e9d19f21-b008-4561-afb7-2947da5ee652)

New：
![PixPin_2024-10-22_23-13-54](https://github.com/user-attachments/assets/0cb8bce6-177a-4f30-bed4-aa818531e5fb)

**Comment by EricZhou05** [comment]
![image](https://github.com/user-attachments/assets/69380817-394a-40b2-847f-393ed6e8d4f1)

Bugs occur for versions 0.2.3 and above

**Comment by pythongosssss** [comment]
fixed thanks to @DrJKL
https://github.com/pythongosssss/ComfyUI-Custom-Scripts/pull/368
