### ISSUE TITLE
"Show Image Feed" button replacing or covering the queue image gen options.

### ISSUE THREAD

**Issue by danganbenpa** [pythongosssss/ComfyUI-Custom-Scripts#377]
![image](https://github.com/user-attachments/assets/5204066e-65a9-46b3-a5a4-c11113a3b8e1)

I can't figure out how to solve this beyond removing the entire thing from ComfyUI. If you have a solution or an update that would help a lot

**Comment by pythongosssss** [comment]
The button should now only show when the feed is closed.
If you dont want the button to show when it is closed, set the "image feed location" setting to "Hidden"
