### ISSUE TITLE
math expression node question: add support for "round" and/or make a rounding node

### ISSUE THREAD

**Issue by aegis72** [pythongosssss/ComfyUI-Custom-Scripts#38]
First, thank you for making these. secondly, other than PMDAS, what other math can I do with this node? 

The reason is I am making a node setup that needs to make an image divisible by 16 on each side before passing to P2LDGAN to create line art. It seems as if python-style "round()" won't work inside this node.

I used the Math Expression node to try to do "round(a / 16) * 16" for the X and Y, after first resizing the image to 1024 on the X side. In this way, I hope to deliver to P2LDGAN a number divisible by 16, and to use this integer for the latent image size as well.

I realize that the rounding happens when it is turned from a float to an Int, but that doesn't work for this situation. f/e, the image shown here, of a Chun li I drew and want to restyle, reduces (without an initial round) to 680x1024, which means the 680 divides by 16 to 42.5.  

My nodes look like so:

![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/118572301/e4e2cfc0-c741-4c4b-bc0a-3668cdcbf284)

And when I run them, This error below is what I get in the console. It dies at the math expression node due to the "round()". If I remove round, it progresses but then the number isn't divisible by 16 anymore. 

Any idea on how I might round the value of (a/16)?

```
got prompt
X val Float is:: 1024.0
Y val Float is:: 1542.0
!!! Exception during processing !!!
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts\py\math_expression.py", line 86, in evaluate
    r = eval_expr(node)
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts\py\math_expression.py", line 70, in eval_expr
    return operators[type(node.op)](eval_expr(node.left), eval_expr(node.right))
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts\py\math_expression.py", line 84, in eval_expr
    raise TypeError(node)
TypeError: <ast.Call object at 0x0000029285A96A70>
```

**Comment by pythongosssss** [comment]
For rounding, you can use floor division (I've just pushed a fix for this as it wasnt working correctly)
![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/125205205/84de7565-fd71-4a62-beb9-ec1878652b09)

`a // b` will round down
`-(a // -b)` will round up

The node supports:
`+ - * /`
`//` floor division
`**` power
`^` xor
`%` mod

**Comment by pythongosssss** [comment]
To make it easier, I've added support for:
 `round(num, decimals?)`
`ceil(num)`
`floor(num)`

![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/125205205/77c72aa2-f4b1-45b0-96a8-cc6438966d55)
