### ISSUE TITLE
导出图片时，背景只占了左上角

### ISSUE THREAD

**Issue by clhui** [pythongosssss/ComfyUI-Custom-Scripts#381]
Frontend Version
[ComfyUI v0.2.4-5-gaf8cf79](https://github.com/comfyanonymous/ComfyUI)
[ComfyUI_frontend v1.3.11](https://github.com/Comfy-Org/ComfyUI_frontend)

Expected Behavior
预期背景是同一个颜色
workflow (1)

Actual Behavior
导出的图片背景只有左上角有颜色，连接线也没显示

Steps to Reproduce
WX20241029-154432@2x

Debug Logs
无
Browser Logs
无

Setting JSON
[comfy.settings.json](https://github.com/user-attachments/files/17553387/comfy.settings.json)
comfy.settings.json

What browsers do you use to access the UI ?
Google Chrome

Other
No response

**Comment by clhui** [comment]
![image](https://github.com/user-attachments/assets/3f48295e-672c-477d-bb23-b9f0accb3d54)

**Comment by pythongosssss** [comment]
This should now be fixed

**Comment by clhui** [comment]
谢谢
