### ISSUE TITLE
"Manage Custom Words" and "Widget and Property Default" menus not opening.

### ISSUE THREAD

**Issue by Hujikuio** [pythongosssss/ComfyUI-Custom-Scripts#382]
I remade a fresh portable comfyui install and still have this issue, tried in multiple browsers as well. The browser console log states that the autocompleter.js is not a function and that the server cannot be found.

<img width="395" alt="log" src="https://github.com/user-attachments/assets/1a7cf366-8259-434a-9792-1778e60ee2a3">

**Comment by klromans557** [comment]
Having the same problem on a fresh install of ComfyUI through SwarmUI

**Comment by mingwusuowei** [comment]
ComfyUI-Custom-Scripts\web\js\autocompleter.js
495行
`
								app.ui.settings.element.close();
`
改
`
								if (typeof app.ui.settings.element.close === "function") {
									app.ui.settings.element.close();
								} else {
									app.ui.settings.element.style.display = "none";
								}
`

**Comment by Hujikuio** [comment]
> ComfyUI-Custom-Scripts\web\js\autocompleter.js 495行 `app.ui.settings.element.close();` 改 `if (typeof app.ui.settings.element.close === "function") { app.ui.settings.element.close(); } else { app.ui.settings.element.style.display = "none"; }`

@pythongosssss This seems to fix the issue. I needed to replace the same element.close function in widgetDefaults.js as well though to get the other menu working. Are there any other scripts that I should update the function in as well?

**Comment by klromans557** [comment]
Can confirm! After making the same change in both autocompleter.js (ln 495) and widgetDefaults.js (ln 271) I am now able to load the Custom Autocomplete Words menu again.

**Comment by pythongosssss** [comment]
Thanks, i've updated the broken bits now!
