### ISSUE TITLE
Cannot be completed properly

### ISSUE THREAD

**Issue by oywenjun11** [pythongosssss/ComfyUI-Custom-Scripts#385]
Hello, when I use the plug-in for word completion, it has not been able to complete normally, only one word display can be selected, how to solve this, thank you in advance for your answer
![Screenshot from 2024-11-05 11-18-08](https://github.com/user-attachments/assets/8bf2b942-3415-4a49-ab24-879d2a7fb8f3)
![Screenshot from 2024-11-05 11-17-53](https://github.com/user-attachments/assets/f2b5642d-7906-41e1-a0e1-b8ddcac8a4b7)

**Comment by ionizer** [comment]
I guess you need to try going into settings and click on "Manage Custom Words". But in my case, clicking the button throws an error
![image](https://github.com/user-attachments/assets/8c7d71d8-5227-41f0-9ab5-f6edceb82fde)

**Comment by pythongosssss** [comment]
The issue with the autocomplete setting should now be fixed, assuming this was the issue for not having any entries
