### ISSUE TITLE
Would like to have an option to hide the Image feed button

### ISSUE THREAD

**Issue by da2el-ai** [pythongosssss/ComfyUI-Custom-Scripts#393]
I don't use the Image feed feature, so I would like to have a setting option to hide the Image feed button.

**Comment by Xenodimensional** [comment]
+1

**Comment by pythongosssss** [comment]
Have you tried the setting "Image Feed Location" -> "Hidden"?

**Comment by da2el-ai** [comment]
Thank you!!
