### ISSUE TITLE
Not an issue just a question, void if you have no time to answer.

### ISSUE THREAD

**Issue by AeroliteAI** [pythongosssss/ComfyUI-Custom-Scripts#394]
Is there a way of setting a default app to open images from the image feed instead of it opening my default browser? when i middle mouse click the image it opens in my default browser, I'm not sure if this is just a web thing or if you implemented that into the plugin.

**Comment by pythongosssss** [comment]
That is just how browsers work when you open images, there might be a workaround by forcing a download but not something simple.
