### ISSUE TITLE
Checkpoint Loader does not output checkpoint as text

### ISSUE THREAD

**Issue by fhaifhai** [pythongosssss/ComfyUI-Custom-Scripts#399]
I am trying to embed metadata into my generations - therefore I wanted to output that checkpoint name from checkpoint loader, but it does not show any text when I try, even with several nodes to show text. any ideas what might be the problem?
![Screenshot 2024-12-08 143223](https://github.com/user-attachments/assets/62070a85-8e54-42eb-9843-60afc25e9ccb)

**Comment by pythongosssss** [comment]
That output text is the example prompt, not the filename (in the screenshot you have none, you can name files [checkpointname].txt or /[checkpointname]/somefilename.txt, or manage it via right click -> view checkpoint info)
