### ISSUE TITLE
NODE_CLASS_MAPPINGS

### ISSUE THREAD

**Issue by TheNeObr** [pythongosssss/ComfyUI-Custom-Scripts#4]
erro when i load comfyui 

"D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\anime-segmentation.py module for custom nodes due to the lack of NODE_CLASS_MAPPINGS"

did I do something wrong ?

**Comment by pythongosssss** [comment]
When you downloaded it, did you download the raw file or the html?
Try this:

https://raw.githubusercontent.com/pythongosssss/ComfyUI-Custom-Scripts/main/anime-segmentation/anime_segmentation.py

**Comment by TheNeObr** [comment]
> When you downloaded it, did you download the raw file or the html? Try this:
> 
> https://raw.githubusercontent.com/pythongosssss/ComfyUI-Custom-Scripts/main/anime-segmentation/anime_segmentation.py

i git clone ur repo and just move the files.....

with ur file 

Traceback (most recent call last):
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1119, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\SD\ComfyUI_windows_portable\ComfyUI\custom_nodes\anime_segmentation.py", line 10, in <module>
    from comfy_extras.anime_segmentation.train import AnimeSegmentation
ModuleNotFoundError: No module named 'comfy_extras.anime_segmentation'

Cannot import D:\SD\ComfyUI_windows_portable\ComfyUI\custom_nodes\anime_segmentation.py module for custom nodes: No module named 'comfy_extras.anime_segmentation'

**Comment by pythongosssss** [comment]
Have you got the animesegmentation repo in the comfy extras folder - the instructions for the node are here:
https://github.com/pythongosssss/ComfyUI-Custom-Scripts/blob/main/anime-segmentation/README.md

**Comment by TheNeObr** [comment]
i redoo again and works, i forgot the model. tks
