### ISSUE TITLE
Vulnerability Report for ComfyUI-Custom-Scripts Plugin

### ISSUE THREAD

**Issue by boy-hack** [pythongosssss/ComfyUI-Custom-Scripts#400]
I would like to report an arbitrary file read vulnerability. Considering that the plugin has a wide impact, could you please leave your contact information or enable the GitHub security option? I will report it there.

**Comment by oxysoft** [comment]
Does this only affect people with `--listen` ? Sounds concerning

**Comment by pythongosssss** [comment]
Hi, this should now be resolved, thanks. If you find any other issues please let me know at
pythongosssss@proton.me

**Comment by boy-hack** [comment]
It seems to have been fixed, can you apply for a CVE number for this vulnerability?
