### ISSUE TITLE
Add icon to identify locked nodes

### ISSUE THREAD

**Issue by andreszs** [pythongosssss/ComfyUI-Custom-Scripts#41]
The **lock node** feature is very useful, however, it's not easy to remember which nodes are locked. I'm constantly trying to move or resize locked nodes only to realize they can't be moved nor resized.

Adding a small [**icon**](https://pictogrammers.com/library/mdi/icon/lock-outline/) to the locked nodes would be really helpful, here's a sample:

![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/10298071/7f373024-9805-4328-84f0-5a28ef3c4f04)

**Comment by pythongosssss** [comment]
![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/125205205/de85686a-d6f5-4e30-8504-812bf5cb09fb)
