### ISSUE TITLE
Text fields of text encoders are messed up in exported workflow images

### ISSUE THREAD

**Issue by artyfacialintelagent** [pythongosssss/ComfyUI-Custom-Scripts#42]
The text input fields for CLIP_G and CLIP_L of CLIPTextEncode and CLIPTextEncodeSDXL usually get messed up in various ways when exporting workflow images. They can appear below the node box or overlayed on top of node inputs. This happens for both png and svg exports, although in slightly different ways. They also appear to remember their previous in-widget values after being changed to an external string primitive.

Below are some simple examples. In image 1 the three text fields contain aaaa, bbbb and cccc. Then I switch to external inputs and put dddd, eeee and ffff in the text inputs.

![workflow (16)](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/137619889/a13aaa86-06ec-4df8-97fd-c47ecc9f9afd)

![workflow (17)](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/137619889/1996223f-196d-4a42-ae73-e60b2300adba)

**Comment by andreszs** [comment]
I'm also dealing with problems where the textboxes and textareas end up in the wrong spots when I drag or zoom the viewport. Usually, shifting the viewport around helps fix it, but honestly, it's still pretty annoying.

I never associated this error to the Custom Scripts plugin, I assumed it was an error from Comfy itself.

**Comment by artyfacialintelagent** [comment]
Yes, it's quite possible that the root cause is in vanilla ComfyUI, which seems to place scaled and translated HTML textarea nodes on top of the drawn canvas in a hacky way. That is definitely not the fault of Custom Scripts. This issue just concerns the export workflow image functionality of Custom Scripts (which may need some additional hacky overrides of its own).

**Comment by pythongosssss** [comment]
@artyfacialintelagent I've (hopefully) fixed the positioning of textareas in PNG exports, and stopped rendering hidden ones.
I wasnt able to reproduce any positioning issues with SVG (only the rendering hidden textareas)

@andreszs This script shouldnt impact normal use of the text areas, it only should only do something for a single frame after you do an export, if you can provide any more info on that let me know an I can look into it.

**Comment by artyfacialintelagent** [comment]
@pythongosssss Exports looking great now, thanks for the quick fix!
