### ISSUE TITLE
[Error] Loading aborted due to error reloading workflow data

### ISSUE THREAD

**Issue by am4nr** [pythongosssss/ComfyUI-Custom-Scripts#43]
I'm trying to get my local installation of ComfyUI up to date after using it in Colab for some time. Whenever i try to load a workflow i get following error. I am using win11 and the most up to date version of Custom Scripts as of writing this (32c9381). Besides Custom Scripts im using following custom nodes:

- https://github.com/melMass/comfy_mtb
- https://github.com/Fannovel16/comfyui_controlnet_aux
- https://github.com/WASasquatch/was-node-suite-comfyui
- https://github.com/ltdrdata/ComfyUI-Manager

```
Loading aborted due to error reloading workflow data

TypeError: can't access property "submenu", v is null

set@http://127.0.0.1:8188/extensions/pysssss/CustomScripts/betterCombos.js:160:11
LGraphNode.prototype.configure@http://127.0.0.1:8188/lib/litegraph.core.js:2542:7
LGraph.prototype.configure@http://127.0.0.1:8188/lib/litegraph.core.js:2240:26
init/LGraph.prototype.configure@http://127.0.0.1:8188/extensions/pysssss/CustomScripts/reroutePrimitive.js:14:29
init/LGraph.prototype.configure@http://127.0.0.1:8188/extensions/pysssss/CustomScripts/snapToGrid.js:53:21
loadGraphData@http://127.0.0.1:8188/scripts/app.js:1227:15
handleFile/reader.onload@http://127.0.0.1:8188/scripts/app.js:1535:10

This may be due to the following script:
/extensions/pysssss/CustomScripts/betterCombos.js
```

Edit: it seems to only happen to when i load some workflows, [this one for example](https://pastebin.com/raw/N05ezdjS)

Edit2: Has something to do with the Loraloader, i dont have the Lora installed locally that i used in the workflow. even after installing the lora locally it didnt work only after removing the LoraLoader i could import the workflow locally
![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/11098327/4ff17435-e4ff-4493-8520-dc532f6ca2f2)

**Comment by pythongosssss** [comment]
This should now be fixed
