### ISSUE TITLE
Bug when connecting nodes

### ISSUE THREAD

**Issue by rethink-studios** [pythongosssss/ComfyUI-Custom-Scripts#46]
I was working with a new workflow, and noticed that when I left-click off the input button, sometimes the SHOW TEXT node gets dragged with the cursor.

Also, after the first connection with a Show Text node, if I drag off of a clip node to automatically connect the Show Text node, Show Text drops without connecting..

link:
https://www.dropbox.com/s/8i1hcoqvp10sfu4/COMFYUI_LEFT_CLICK_CONNECTION_BUG_PYSSSS.mp4?dl=0

**Comment by pythongosssss** [comment]
When this happens, are you able to go to the settings menu -> View Logs
And export the logs from there please

And what type of node is that positive prompt? It looks like a primitive? If so you cant connect primitives to "normal" nodes, this pr: https://github.com/comfyanonymous/ComfyUI/pull/1104 should hopefully fix that

**Comment by rethink-studios** [comment]
Yup, it's a primitive. Apologies!

How would I integrate pr:#1104? (I've already updated to the latest comfy)

**Comment by pythongosssss** [comment]
Personally I would wait for it to be merged into master else you're going to need to be managing your own branch.
As an alternative, you can use my reroute-primitive:
![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/125205205/07c022a2-b027-4613-8482-69afc20b1863)

**Comment by pythongosssss** [comment]
@rethink-studios The pending PR for ComfyUI has been merged so this issue should now be resolved
