### ISSUE TITLE
Custom notes issues

### ISSUE THREAD

**Issue by alexopus** [pythongosssss/ComfyUI-Custom-Scripts#48]
Thanks a lot for these scripts and especially for the recently added custom notes on Loras, these are very useful!

I found a few issues with the custom notes feature.

If my note contain:
```
goompa
https://civitai.com/models/55475/sxz-slavic-fantasy-style
```
The link is not clickable. It would be nice if it were.

Additionally, if I change the note to be:
```
https://civitai.com/models/55475/sxz-slavic-fantasy-style
goompa
```
, then the link is clickable, but "goompa" is concatenated with the URL:

![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/25933468/bd79e793-4299-4915-b873-5b1306c1ac5f).

Which I guess is unintentional, or?

(I realize there is no need for the civitai link in this particular case, since it is detected by your extension automatically, but I would still like to be able to store links in custom note, if certain lora is only on huggingface or any other random site),

As a side question, are you also planning on adding civitai link and custom notes to your Checkpoint loader too :)?

**Comment by pythongosssss** [comment]
I've improved the handling of links in custom notes, hopefully that resolves your issue.

Yes, I'll add it to the checkpoint loader but I'll need to refactor the code a bit first as it's a bit of a mess!

**Comment by alexopus** [comment]
Thanks, it is working as expected now!

**Comment by pythongosssss** [comment]
@alexopus I've added support for checkpoint info now
![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/125205205/038a8b2b-2027-4873-911a-9267255b73a8)

**Comment by alexopus** [comment]
Awesome, thanks!
