### ISSUE TITLE
Lack of __init__.py

### ISSUE THREAD

**Issue by rular099** [pythongosssss/ComfyUI-Custom-Scripts#5]
I'm sorry but there is no __init__.py in this package. 
An empty one will cause "Skip /path/to/ComfyUI-Custom-Scripts module for custom nodes due to the lack of NODE_CLASS_MAPPINGS."

**Comment by pythongosssss** [comment]
The majority of scripts in this repo are frontend only, so go into web/extensions 
For the few that go into custom_nodes you can just put the py files in there, and they will generally need additional setup/requirements downloading (hopefully covered in the specific script readme!)

**Comment by rular099** [comment]
> The majority of scripts in this repo are frontend only, so go into web/extensions For the few that go into custom_nodes you can just put the py files in there, and they will generally need additional setup/requirements downloading (hopefully covered in the specific script readme!)

It works!
