### ISSUE TITLE
Submenus not working

### ISSUE THREAD

**Issue by clyce** [pythongosssss/ComfyUI-Custom-Scripts#53]
Hello, 

I have enabled the "Enable submenu in Custom Nodes" option
![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/1068472/f7bffe54-7155-43cf-a5b9-60a665e200b8)

But when I am trying to select LoRAs/Checkpoints, it is still in a plain list：
![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/1068472/1f1eeebc-2acb-4af0-a259-63664ac91a9c)

Am I missing anything to config?

**Comment by pythongosssss** [comment]
Would you be able to run the following command in your browsers console, and let me know the output:
`console.log(navigator.platform || navigator.userAgent, (navigator.platform || navigator.userAgent).includes("Win") ? "\\" : "/")`

My guess is that it isnt choosing the correct path separator to split by

**Comment by clyce** [comment]
Ah, I think yes. It is showing as `Win32 \`, while in the listed menu, the seperator is actually `/` as in POSIX. May be a Regex or an explicit path resolving js lib can handle it better?

**Comment by pythongosssss** [comment]
Would you please be able to share the output of the command so I can see what OS/user agent it says you are using

**Comment by clyce** [comment]
Sure, it is `'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36 Edg/118.0.0.0'`

(The original output is exactly `Edg` instead of edge)

**Comment by clyce** [comment]
Thank you!

**Comment by pythongosssss** [comment]
I've pushed an update for this, hopefully resolves it for you!
