### ISSUE TITLE
Limit the trigger of autocomplete window a lil bit?

### ISSUE THREAD

**Issue by alexopus** [pythongosssss/ComfyUI-Custom-Scripts#54]
The new autocomplete feature is awesome!
But would it be possible to limit when it appears a little bit. For example, if I just navigate through my prompt with the arrow keys, it will appear even if I'm just passing through a word, and for certain directions (up/down) it will even hinder further movement.

For example, here I am pressing only arrow keys (mostly only up/down):

https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/25933468/6f54806a-27a0-4342-b2b8-de3085382b29

So the movement through the text gets "stuck" in the autocomplete. 

Not sure what is best, maybe exclude arrow keys to trigger the initial appearance?

**Comment by pythongosssss** [comment]
Excluding arrows seems like a good solution, i've made that update! Thanks for the feedback.
