### ISSUE TITLE
New Idea

### ISSUE THREAD

**Issue by RyanSHS6** [pythongosssss/ComfyUI-Custom-Scripts#57]
Hello, friend, I like your work very much, can you add a reference snap line for the node to it, maybe a guide line that appears when snapping with PS transformation, thank you!

**Comment by pythongosssss** [comment]
Hi,
Would you be able to expand on/show a design for your suggestion as I'm not quite sure what you mean, thanks!

**Comment by RyanSHS6** [comment]
Maybe like this!
![snap](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/118988972/26d5b9c2-ab5d-4ff8-9668-d1577587dace)

**Comment by pythongosssss** [comment]
I'll take a look, however I think it might be quite challenging with LiteGraph

**Comment by RyanSHS6** [comment]
I know this project, no wonder I have a familiar feeling when I look at comfyui, I tried to beautify the UI, but my skills are limited and I can't do more operations o,O 
![2140c15376aa788d9f1220565ae5487](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/118988972/14fba00a-35f5-466e-b32d-e378c1d81211)

**Comment by pythongosssss** [comment]
Thanks to @choey for implementing a similar feature
https://github.com/pythongosssss/ComfyUI-Custom-Scripts/pull/228
