### ISSUE TITLE
LoadLora suggestion

### ISSUE THREAD

**Issue by MrFreekstorm** [pythongosssss/ComfyUI-Custom-Scripts#59]
Love your LoraLoader, but sometimes I want to turn a lora on and off without unwiring it, setting up switches etc seems like too much trouble so I made an edit to your code that you might want to consider including in the future.

`class LoraLoaderWithImages(LoraLoader):
    @classmethod
    def INPUT_TYPES(s):
        types = super().INPUT_TYPES()
        names = types["required"]["lora_name"][0]
        populate_items(names, "loras")
        names.insert(0, {"content": "None","image": None,})
        return types

    def load_lora(self, **kwargs):
        kwargs["lora_name"] = kwargs["lora_name"]["content"]
        if (kwargs["lora_name"]=="None"):
            kwargs["strength_model"]=0
            kwargs["strength_clip"]=0
        return super().load_lora(**kwargs)
`
This allows you to select None and bypass the Lora without having to rewire around it or set the weights to zero.

**Comment by pythongosssss** [comment]
You can use "Bypass" or CTRL+B with the node selected to bypass the LoRA node, this is a standard feature that was introduced semi-recently - it works with every node and can be useful for this

**Comment by MrFreekstorm** [comment]
I didnt realise that, thank you.
