### ISSUE TITLE
无法使用wd14tager

### ISSUE THREAD

**Issue by laojingwei** [pythongosssss/ComfyUI-Custom-Scripts#6]
No problem with startup, no problem with node display, but when you click Run, no picture text information is displayed under WD14Tagger, console has an error

Both cuda and cudnn are the latest versions, and I have also installed this TensorRT-8.6.0.12.Windows10.x86_64. Cuda-12.0, may I ask what else I need to do to use this tag
![111](https://user-images.githubusercontent.com/39719779/232111395-c21aa760-57f1-4fbd-b411-01b4ed175df5.png)
![222](https://user-images.githubusercontent.com/39719779/232111406-7bab24e4-f55f-484f-96cb-6454c64d6c7f.png)

got prompt
Traceback (most recent call last):
  File "F:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 182, in execute
    executed += recursive_execute(self.server, prompt, self.outputs, x, extra_data)
  File "F:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 67, in recursive_execute
    outputs[unique_id] = getattr(obj, obj.FUNCTION)(**input_data_all)
  File "F:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\wd14-tagger.py", line 133, in tag
    res = tag(image, model, threshold, character_threshold, exclude_tags)
  File "F:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\wd14-tagger.py", line 37, in tag
    model = InferenceSession(name, providers=ort.get_available_providers())
  File "F:\ComfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 360, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "F:\ComfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 408, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1106 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load "F:\ComfyUI\ComfyUI_windows_portable\python_embeded\lib\site-packages\onnxruntime\capi\onnxruntime_providers_tensorrt.dll"

**Comment by pythongosssss** [comment]
Seems like some incompatibility between the DLLs, there are a fair few reports of these errors around, e.g. https://github.com/microsoft/onnxruntime/issues/11826

Can you check that your versions match the onnx requirements
Or you might want to try uninstalling onnxruntime-gpu if you installed that, and just using onnxruntime

**Comment by laojingwei** [comment]
Thanks, I'll try it, it feels so good, I'd love to have it

**Comment by Natotela** [comment]
> Seems like some incompatibility between the DLLs, there are a fair few reports of these errors around, e.g. [microsoft/onnxruntime#11826](https://github.com/microsoft/onnxruntime/issues/11826)
> 
> Or you might want to try uninstalling onnxruntime-gpu if you installed that, and just using onnxruntime
> 
> This seems to provide some more info too: [danielgatis/rembg#312 (comment)](https://github.com/danielgatis/rembg/issues/312#issuecomment-1465316591)

worked for me, 10x

**Comment by pythongosssss** [comment]
I've moved node to a new repo, if there are any more issues please reopen an issue there
https://github.com/pythongosssss/ComfyUI-WD14-Tagger
