### ISSUE TITLE
Node name for S&R resolves to object Object

### ISSUE THREAD

**Issue by alexopus** [pythongosssss/ComfyUI-Custom-Scripts#61]
I configure a Save Image node file name as `%date:yyyyMMdd_hhmmss%_%seed.value%_%PyLdr.ckpt_name%`:

![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/25933468/f2764839-a0e8-4e0c-ae9a-fbfefd477e80)

However, the resulting file name is: `20230902_000927_1110874602069990_[object Object]_00001_.png`.

It works fine with other nodes, but Checkpoint Loader 🐍 returns "object Object".

Any idea what's going wrong?

**Comment by pythongosssss** [comment]
Ah this is due to how my checkpoint/lora loader works
I'll need to have a think about how to fix this one as it probably wont be simple!

**Comment by pythongosssss** [comment]
This should now be fixed
