### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Tikishark777** [pythongosssss/ComfyUI-Custom-Scripts#64]
Is it possible that when using the "Show Text" node, the text is exported to an Excel/spreadsheet file?  I'm currently using the mode in combination with another custom mode that accepts input into ChatGPT as a question and then outputs the answer to the "Show Text" node as well as to the Ksampler to generate an image.  It would be cool to be able to save the text output as prompts later.  Also, on a side note, even when I set the dimensions of the "Show Text" box, it always reverts back to 400x80.  Is there a way to lock in the dimensions to 400x400?

**Comment by pythongosssss** [comment]
I don't think I would want to do something specific with Excel (I don't have it), but I could have a generic "WriteText" node that you could use to append text to a CSV file which Excel supports.

I've fixed the issue with the Show Text node resizing

**Comment by Tikishark777** [comment]
Yes, a general text output file option would be a great feature and thank you for fixing the box dimension issue. I appreciate your hard work.

**Comment by pythongosssss** [comment]
![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/125205205/9ef905c7-d93a-47df-8e09-18448ca10dd3)
I've added Load Text & Save Text nodes

You can control the allowed directories from `custom_nodes/ComfyUI-Custom-Scripts/user/text_file_dirs.json`
e.g. to allow files in C:/Test to be read/written
![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/125205205/b50ceb1a-9065-4dd3-a286-7cf21ae8b4c4)

**Comment by Tikishark777** [comment]
I followed your example and created a folder at c:/Test, but nothing is being exported?  I have the selector set to test. The nodes are connected where my chatgpt node is outputting a string, I connected to show text to this and connecting the string to the save text node. Also, would you be able to show me the format for setting the save folder in this path c:/users/documents/hold?  Ty

**Comment by pythongosssss** [comment]
![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/125205205/49aa4cc1-ed3f-4488-98d6-5335f7c3a792)
![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/125205205/01568c62-0cfd-4e88-8b3d-d825269a942d)

```json
{
	"input": "$input/**/*.txt",
	"output": "$output/**/*.txt",
	"temp": "$temp/**/*.txt",
	"hold": "C:/Users/documents/hold/**/*.txt"
}
```

**Comment by Tikishark777** [comment]
Worked perfectly. Ty
