### ISSUE TITLE
feature request reverse route

### ISSUE THREAD

**Issue by hightechpresha** [pythongosssss/ComfyUI-Custom-Scripts#65]
Hi, as a fan of clean workflows, a feature request that should help many of us: A function to rotate reroutes by 90 degrees or 180 degrees. This way you could also make links to left.

![reverse-route](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/20563696/a9001ad8-9b9f-4d9d-9f4e-3148cf951726)

**Comment by pvp-by** [comment]
There is a custom node, it's not perfect, but it can do what you want. but I use it very seldom, its controls are too unfriendly in the default settings.

https://github.com/rgthree/rgthree-comfy#reroute

**Comment by pythongosssss** [comment]
There are now various other reroutes that allow for this
