### ISSUE TITLE
Can Autocomplete support chinese translation file？

### ISSUE THREAD

**Issue by RedDestiny** [pythongosssss/ComfyUI-Custom-Scripts#66]
Can Autocomplete support chinese translation file？
自动补全功能可以支持中文翻译文件吗？
[Tags-zh-full-pack.csv](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/files/12531636/Tags-zh-full-pack.csv)

**Comment by pythongosssss** [comment]
Do you mean you want to be able to enter a word in Chinese and it be treated as an alias for another word?
For example, you write `绷带` and `bandage` is added?

**Comment by RedDestiny** [comment]
> Do you mean you want to be able to enter a word in Chinese and it be treated as an alias for another word? For example, you write `绷带` and `bandage` is added?

yes。

**Comment by pythongosssss** [comment]
I've added support for aliases https://github.com/pythongosssss/ComfyUI-Custom-Scripts/commit/d0c3169aa0176d13fc0268ccd49290a53cb74140
If you paste that list into the custom word list, that should hopefully work for you
![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/125205205/a6568371-a2df-4ca6-9d19-8544d1ce7d3e)

![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/125205205/165f4daf-975d-4df3-9187-09c0afd6003b)

**Comment by RedDestiny** [comment]
It works well，thanks。
”If i am typing Chinese，it can also show the english txt“ will works better。

**Comment by pythongosssss** [comment]
![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/125205205/b5ae6844-97ae-4d55-855e-3d774d6a57f8)

**Comment by Sostay** [comment]
> It works well，thanks。 ”If i am typing Chinese，it can also show the english txt“ will works better。

怎么实现的啊请问？中文词库是放哪里的？
