### ISSUE TITLE
Imagefeed column count limited to 10

### ISSUE THREAD

**Issue by vraagje** [pythongosssss/ComfyUI-Custom-Scripts#67]
The image feed is ideal for swiftly locating a previously used 'good' seed when working with random seeds. Therefore, I prefer to keep my image feed size as compact as possible during generation. However, due to the maximum column limit of 10, it results in significant black margins between the images. Is there a way to adjust the 'max' columns value to a larger number using a setting or some other method? Your assistance would be greatly appreciated.

**Comment by pythongosssss** [comment]
Would increasing it to 20 be enough for you?

**Comment by vraagje** [comment]
I checked and changed the "imagefeed.js" myself to "max:40" and that would do it for me.  My 27" screen resolution is set to 3840x2160. But I can imagine some people use have 30" or bigger or dual screens, then 40 may also be not enough. On the other hand, 13" laptops may only need max 10. So I guess a slider from 1 to 80? makes sliding a bit annoying for the laptop users. Therefor I guess a "max" setting in the preferences would be most UI friendly. Or a 'smart' system based on the screen resolution or size? Or maybe a slider with only 16 stops where 1-10 = 1-10, but 11=15, 12=20, 13=30, 14=40, 15=50, 16=80...

**Comment by pythongosssss** [comment]
![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/125205205/e08925d6-8232-4b24-b595-d0570c367411)
You can now click the label to set a custom column count

**Comment by vraagje** [comment]
Thank you!, it works perfectlyFrank From: pythongosssssSent: vrijdag 8 september 2023 20:51To: pythongosssss/ComfyUI-Custom-ScriptsCc: Frank; AuthorSubject: Re: [pythongosssss/ComfyUI-Custom-Scripts] Imagefeed column count limited to 10 (Issue #67) You can now click the label to set a custom column count—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
