### ISSUE TITLE
Creation of reroute node via wheel button accidentally disconnect nodes

### ISSUE THREAD

**Issue by Melaton** [pythongosssss/ComfyUI-Custom-Scripts#69]
I move canvas by mouse wheel button. Sometimes I accidentally click on slot zones, which disconnect nodes by creating reroute nodes. Due to scale of node frameworks and use of pin-function such incidents sometimes extremely inconspicuous and difficult to find.
Please, add to settings possibility turn off reroute creation by wheel button.

**Comment by pythongosssss** [comment]
Added
![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/125205205/91727e84-dab4-401f-93b4-66058a7d7edb)
