### ISSUE TITLE
I need Install.py

### ISSUE THREAD

**Issue by aipman** [pythongosssss/ComfyUI-Custom-Scripts#7]
We hope to have an Install.py that is as convenient as installing other custom nodes, helping us quickly install all scripts.

**Comment by wyrde** [comment]
This repo isn't a suite of nodes meant to be installed all at once, Many are front-end extensions that aren't controlled by python anyway. A few are even a mix. Put the `.py` files in `custom_nodes` and `.js` files in `web/extensions`

**Comment by aipman** [comment]
Okay, every time he installs, he has to manipulate many files, such as installing on the cloud

**Comment by Natotela** [comment]
> This repo isn't a suite of nodes meant to be installed all at once, Many are front-end extensions that aren't controlled by python anyway. A few are even a mix. Put the `.py` files in `custom_nodes` and `.js` files in `web/extensions`

you could just put it in the readme description :-D 
10x mate
