### ISSUE TITLE
Workflow images strip newlines from multiline text fields

### ISSUE THREAD

**Issue by ali1234** [pythongosssss/ComfyUI-Custom-Scripts#70]
To reproduce:

1. Clear workflow
2. Add some multiline node
3. Type some lines in it
4. Screenshot

Result: the nodes in the screenshot have no newlines:

![workflow png from right click menu](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/651970/ea148c0d-c22e-45a3-af86-616a8e2d8759)

Expected result:

![screenshot made with external tool](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/651970/fd9e472a-cadc-4daa-b9e0-658ceec62699)

The newlines are preserved in the embedded workflow. They just don't show in the image.

**Comment by pythongosssss** [comment]
This should now be fixed
