### ISSUE TITLE
Feature request: CSV filetype support for autocomplete

### ISSUE THREAD

**Issue by Jongulo** [pythongosssss/ComfyUI-Custom-Scripts#71]
Most tag lists use a CSV file type so it would make sense to support this for autocomplete.
As well as the fact that the autocomplete for A1111 uses it.

**Comment by Jongulo** [comment]
https://cdn.discordapp.com/attachments/1086767639763898458/1092754564656136192/fluffyrock.csv

**Comment by pythongosssss** [comment]
I've added support for this format
You can't add it automatically via the url, you'll need to copy and paste the list into the text area

**Comment by Jongulo** [comment]
> I've added support for this format, although I was confused by some of the aliases so if you could please confirm its working as intended
> 
> You can't load the list automatically via the url (discord blocks it), you'll need to copy and paste the list into the text area

Looks like it works, Thank you!
