### ISSUE TITLE
enhancement option for MMB

### ISSUE THREAD

**Issue by pvp-by** [pythongosssss/ComfyUI-Custom-Scripts#73]
Now the middle mouse button adds (MMB) default node "reroute", could you add an option that you can choose which reroute will be added by MMB :
* default 
* [pythongosssss](https://github.com/pythongosssss/ComfyUI-Custom-Scripts#testing-reroute-primitive)
* [rgthree](https://github.com/rgthree/rgthree-comfy#reroute)

what do you think about it ?

**Comment by pythongosssss** [comment]
I've updated the option to support this
![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/125205205/6b474b68-a1ea-4186-be3b-de246720c09f)
I don't have the rgthree one, but as long as it has "Reroute" in the node name it should appear in the list
