### ISSUE TITLE
"Send to workflow..." functionality to emulate AUTO1111/SD.Next agile workflows

### ISSUE THREAD

**Issue by oxysoft** [pythongosssss/ComfyUI-Custom-Scripts#74]
Hi, first I just really wanna say this extension pack is a must have and in my opinion should be directly merged into the official project. These in my opinion are not extensions, but pull requests that should be made for all sorts of essential features. For some reason the UI in Comfy is moving at a snail's pace and almost designed not to be used. I'm really sad that I have to speak so harshly about its UI, because the core underneath and overall ecosystem is a grand slam. Anyone still using or supporting other UIs are literally idiots!!

Anyway just a simple recommendation: it would be great if we could right click on an image output and "send" it to one of the workflows in the user's library as implemented by this plugin. The way this works is pick the one LoadImage node in the graph, or show a list to pick from (or better yet enter a modal view where you can pan around the canvas and click a node to set the image into it, that way it sticks to the node philosophy)

Finally, a special `<loopback>` item could be added at the top of the workflow list which stands for the current workflow.

**Comment by pythongosssss** [comment]
![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/125205205/75b89a0b-4c8c-4654-b58f-7f09f9a805f8)
I've added this, if the workflow you are sending to has multiple load image nodes, if you name one of them with the word "input" in it, e.g. "Load Image (input)" it will use that node, else it'll use the first node. If there is a use case for multiple load image nodes where you want to pick a different one each time I can revisit that.
