### ISSUE TITLE
Primitive reroute nodes are a bit buggy :<

### ISSUE THREAD

**Issue by Ferniclestix** [pythongosssss/ComfyUI-Custom-Scripts#75]
Was trying to make a truely modular workflow and keep finding that the custom Reroute nodes with this node pack are very tempramental, sometimes when closing the text boxes get stuck open when they are using strings and generally misbehave with certain kinds of connections.

**Comment by adloram** [comment]
they're not working for me at all? I can't get them to connect.

**Comment by pythongosssss** [comment]
Reroute primitive was a bit of a failed expirement, i've hidden them and would recommend using a core reroute+primitive nodes
