### ISSUE TITLE
Transparent links if they are not connected to the selected node

### ISSUE THREAD

**Issue by oxysoft** [pythongosssss/ComfyUI-Custom-Scripts#77]
Simple idea: make all the links transparent by default, and fully opaque when when they connect the input or output of the selected node

**Comment by pythongosssss** [comment]
You mean like this?
![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/125205205/d6f66b86-9779-41ae-acd6-d826c414c043)

![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/125205205/ba602059-f536-4a16-86fb-17163c4292b5)

**Comment by pythongosssss** [comment]
No update
