### ISSUE TITLE
Save images from CivitAI (View Info) to LoRA preview

### ISSUE THREAD

**Issue by oxysoft** [pythongosssss/ComfyUI-Custom-Scripts#78]

**Comment by gontz** [comment]
And query for the trigger words and add them as string output

**Comment by pythongosssss** [comment]
I've added a button for "use as preview" to the image
![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/125205205/d0d349fd-a61f-4251-b6dd-b5492aaeed1c)

@gontz if you want to log a separate issue for that idea as it'll be a bigger change that just adding this save image button

**Comment by opensourcefan** [comment]
Just curious if there's a script or option to automatically add all the civitai preview images for your installed loras automatically. I'm doing it one by one but it's going to take forever.
