### ISSUE TITLE
[PR] presetText.js is super useful

### ISSUE THREAD

**Issue by wyrde** [pythongosssss/ComfyUI-Custom-Scripts#8]
Any chance of a PR to get it included in comfy? (: 

I especially like using it to set up a value for a file prefix.

**Comment by pythongosssss** [comment]
I was thinking before being included in comfy there should either be standard text concatenation or maybe I could support doing `@preset-name` in the prompt and replacing that...

As I often want `{my standard negatives}, some, prompt, specific, negatives`

**Comment by wyrde** [comment]
saw what you showed in matrix, looks awesome!

**Comment by pythongosssss** [comment]
The changes are in this repo, i'll leave them for a bit to ensure there arent any bugs and then i'll PR it to comfy repo!

**Comment by pythongosssss** [comment]
An update on this - there have been a few incompatibilities with other extensions and I think having this as a standard in feature in comfy may be able to resolve this, so I'll close this for now but keep it in mind!
