### ISSUE TITLE
Save a group of nodes to a library accessible for quick re-use at any time (drag and drop)

### ISSUE THREAD

**Issue by oxysoft** [pythongosssss/ComfyUI-Custom-Scripts#81]
Hi friends, I think I know what's the big thing missing in our workflows now for agile ComfyUI work: the ability to save a pre-made group of nodes and quickly re-use it at any time. For example, if I want to add ControlNet, I need to add each node myself when I could drag a ControlNet group with several nodes and processors already setup the way I like them. This would pair very well with the workflow library feature you have added in this project.

**Comment by pythongosssss** [comment]
This feature is available via node templates in standard comfyui:
![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/125205205/d06541de-86bd-47a6-8eb6-bda83b6948db)

if you right click on the canvas with some nodes selected, you can save them as a template and then use that in any workflow
