### ISSUE TITLE
Query trigger words of the lora on civitai

### ISSUE THREAD

**Issue by gontz** [pythongosssss/ComfyUI-Custom-Scripts#82]
As a user, I want to see the trigger word(s) of the lora I'm loading. And I would like to output them as a string that I can send to the positive prompt.
If it helps, there is a plugin for Comfyui that does this. But it doesn't offer a preview. 
https://github.com/Extraltodeus/LoadLoraWithTags

Thank you

**Comment by pythongosssss** [comment]
While not exactly what you asked for, this is a more flexible system, I've added the ability to save the trained tags from the view info dialog (you can edit the text in the trained tags area too) and added save selected as example.
![image](https://github.com/user-attachments/assets/889ffc8e-a241-4fd9-a2bf-8d9e4e735d40)

The examples dropdown now autoselects the first one, and outputs the example text
![image](https://github.com/user-attachments/assets/129cbf72-fe3d-4761-aba2-d04beb14a8ac)
