### ISSUE TITLE
Custom location for storing workflows

### ISSUE THREAD

**Issue by alexopus** [pythongosssss/ComfyUI-Custom-Scripts#84]
Right now the saved workflows go to `<comfy dir>/pysssss-workflows`.
Would it be possible to make this configurable, to have them stored elsewhere?

**Comment by pythongosssss** [comment]
You can now specify a custom folder in `ComfyUI-Custom-Scripts/pysssss.json`
e.g. adding
```
	"workflows": {
		"directory": "C:\\ComfyUI-Workflows"
	}
```

This is an example:
https://github.com/pythongosssss/ComfyUI-Custom-Scripts/blob/main/pysssss.example.json

**Comment by alexopus** [comment]
Could you add `pysssss.json` to `.gitignore`?

If I modify it locally, then Manager fails to update this extension because of:
```
Updating failed: /home/user/ComfyUI/custom_nodes/ComfyUI-Custom-Scripts
Cmd('git') failed due to: exit code(128)
cmdline: git pull -v --rebase -- origin
stderr: 'error: cannot pull with rebase: You have unstaged changes.
```

Or is there a different way to solve this?

**Comment by shamowfski** [comment]
If all you are changing is the workflow directtory, I just ended up creating a symlink because my config got overwritten every time I updated (windows).
