### ISSUE TITLE
Switch inputs type to number to set values with scroll wheel

### ISSUE THREAD

**Issue by andreszs** [pythongosssss/ComfyUI-Custom-Scripts#85]
Whenever you double click a numeric value to show the popup dialog to manually set it, the input type is `text`, which means you don't get the native up/down arrows and scroll wheel does nothing.

Switching those inputs to `type="number"` and adding `step="0.05"` would show the arrows, and allow keyboard up/down arrows and mouse wheel to change the value in 0.05 increments/decrements. Also, min and max attributes can limit the values whenever needed. Having to manually type values while you could use the mouse wheel to change them is rather cumbersome.

➡ [Input type number on MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number)

**Comment by pythongosssss** [comment]
The problem with this is you then cant enter expressions, e.g. 
![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/125205205/95f02118-20c5-4972-97b8-49cd6c29a240)

**Comment by pythongosssss** [comment]
I've added an option for this as I guess people may not care about that ^
![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/125205205/ec904315-9a70-4498-85eb-3edeeb39ae8d)
