### ISSUE TITLE
[Feature Request] Add View Info to Lora Loaders from other Custom Nodes.

### ISSUE THREAD

**Issue by brknsoul** [pythongosssss/ComfyUI-Custom-Scripts#89]
This might not be possible without collaboration, but it'd be swell if the View Info feature could be added to other Lora Loaders.

Alternatively, perhaps allow an input that takes any input, allow selection of a widget that node and use that for viewing info.

Currently, I simply use a detached default Lora Loader for a Lora Checker, and Efficiency Node's Lora Stacker.

**Comment by xieve** [comment]
I'm currently using rgthree's Power Prompt node for this, but that means I'm still missing the view info button (which could work exactly the same as for the embeddings)

**Comment by pythongosssss** [comment]
You can use this 
`LoraLoader.lora_name,LoraLoader|pysssss,LoraLoaderModelOnly.lora_name,LoRA Stacker.lora_name.*`
In the setting called _🐍 Model Info - Lora Nodes/Widgets_

This should add support for the stacker, and you can add support for other nodes in the same manner.
