### ISSUE TITLE
LoadText work, but SaveText no work,

### ISSUE THREAD

**Issue by xueqing0622** [pythongosssss/ComfyUI-Custom-Scripts#90]
LoadText work, but SaveText no work,  
even I  change the text_file_dirs.json like this ,
{
	"input": "$input/**/*.txt",
	"output": "F:/ComfyUI/ComfyUI/output/txt/*.txt",
	"temp": "$temp/**/*.txt"
}
LoadText work, but SaveText no work, 

![Sp231005-142211](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/114840118/c0159e22-385d-4a14-8910-956eb5b7ae37)

**Comment by mijuku233** [comment]
Connecting `string` to `Show Text` node can solve this problem

**Comment by xueqing0622** [comment]
Yes, it works now, thx!

**Comment by xueqing0622** [comment]
Yes, it works now, thx!
