### ISSUE TITLE
Widget Defaults

### ISSUE THREAD

**Issue by alexbofa** [pythongosssss/ComfyUI-Custom-Scripts#92]
Hello! 

Please save the [Widget Defaults](https://github.com/pythongosssss/ComfyUI-Custom-Scripts#widget-defaults) settings in a **json** file, not a **cookie**. Like here https://github.com/rgthree/rgthree-comfy/commit/3cbcce52777d9bf0cc01c26917564f6f4a56f4cd

Today there was an incident when my menu disappeared under bookmarks. There was no way to pull it out, I had to clean the cookies at the address http://127.0.0.1:8188. Along with this, the menu settings that were collected for more than a month disappeared :(

![image](https://github.com/pythongosssss/ComfyUI-Custom-Scripts/assets/58225118/22830523-34f9-4f8f-b14d-7ed19b8c1b2c)

**Comment by pvp-by** [comment]
the topic is relevant, I will support this idea with my vote.

**Comment by pythongosssss** [comment]
This is done

**Comment by alexbofa** [comment]
Thanks! 🖤
