### ISSUE TITLE
plz delete user\autocomplete.txt in github, every update will delete my autocomplete.txt

### ISSUE THREAD

**Issue by xueqing0622** [pythongosssss/ComfyUI-Custom-Scripts#95]
plz delete user\autocomplete.txt in github, every update will replace my edited my autocomplete.txt
(just give a readme let user create it himself )

**Comment by xueqing0622** [comment]
someone have a good idea to deal with it?

**Comment by pvp-by** [comment]
its not step for you - only for [pythongosssss](https://github.com/pythongosssss)
need add `autocomplete.txt` to `.gitignore`
add `autocomplete.txt.example` (it doesn't matter that it's empty)
in code check file `autocomplete.txt` (if it exists, do nothing - else, create empty)

profit! `git pull` ignore file and not rewrite.

PS and I in no way want to teach `pythongosssss` (he's already a cool pro).
this is more of a clarification for the author of the issue

**Comment by xueqing0622** [comment]
> its not step for you - only for [pythongosssss](https://githubfast.com/pythongosssss) need add `autocomplete.txt` to `.gitignore` add `autocomplete.txt.example` (it doesn't matter that it's empty) in code check file `autocomplete.txt` (if it exists, do nothing - else, create empty)
> 
> profit! `git pull` ignore file and not rewrite.
> 
> PS and I in no way want to teach `pythongosssss` (he's already a cool pro). this is more of a clarification for the author of the issue

right, but no update for this, 
https://githubfast.com/ltdrdata/ComfyUI-Inspire-Pack/issues/21
just like Inspire-Pack lbw-preset.txt way

**Comment by pythongosssss** [comment]
Thisis done
