### ISSUE TITLE
denoise setting

### ISSUE THREAD

**Issue by dkamajix** [pythongosssss/ComfyUI-Custom-Scripts#96]
Hello,
I want to set a custom denoise setting of .5 in my ksampler (adv)
default is 15
I add .5 then says 0-1
I leave 0.5 and hit enter.
but if I check again for denoise it says 15 again.

how do I know what its actually set to?

**Comment by pythongosssss** [comment]
You can see here the formula for calculating it:
https://comfyui.creamlab.net/guides/f_KSamplerAdvanced_denoise
