### ISSUE TITLE
question: image to text

### ISSUE THREAD

**Issue by drago87** [pythongosssss/ComfyUI-Custom-Scripts#97]
I can't make the image to text work like the example shown here
https://github.com/pythongosssss/ComfyUI-Custom-Scripts#show-text
The load image and the Show text i have found it is the node between them i cant find

**Comment by madvas** [comment]
+1

**Comment by pythongosssss** [comment]
https://github.com/pythongosssss/ComfyUI-WD14-Tagger is what I was using there
