### ISSUE TITLE
Question: String Concat for CLIP Node

### ISSUE THREAD

**Issue by TomLucidor** [pythongosssss/ComfyUI-Custom-Scripts#98]
It is good to see string functions can be used directly in ComfyUI https://github.com/pythongosssss/ComfyUI-Custom-Scripts#string-function
Currently checking out this as a potential solution but not sure if it is still functional or not  https://github.com/comfyanonymous/ComfyUI/issues/133 https://github.com/m957ymj75urz/ComfyUI-Custom-Nodes/

Side note: would CLIP concatenation be different from string concatenation before inserting to CLIP?
Side note 2: combinatorics of LucianoCirino is great https://github.com/LucianoCirino/efficiency-nodes-comfyui

**Comment by pythongosssss** [comment]
You can combine conditionings using Conditioning Combine/Conditioning Concat
