### ISSUE TITLE
Touch events seem to fire twice

### ISSUE THREAD

**Issue by Happ1ness-dev** [pythongosssss/ComfyUI-Custom-Scripts#99]
Hello, I'm using ComfyUI on mobile, and when I installed your custom node, the UI started to behave a little weird. The control panel is resetting it's position after I show or hide the keyboard, besides that, when I try to click some buttons on it, they're being pressed twice. It's not always consistent, sometimes it's enough to just move this panel around to fix it for one touch, but next touches will be registered twice again.

**Comment by Gerkinfeltser** [comment]
> Hello, I'm using ComfyUI on mobile, and when I installed your custom node, the UI started to behave a little weird. The control panel is resetting it's position after I show or hide the keyboard, besides that, when I try to click some buttons on it, they're being pressed twice. It's not always consistent, sometimes it's enough to just move this panel around to fix it for one touch, but next touches will be registered twice again.

I'm seeing this behavior as well.

**Comment by ProcrastinationGiant** [comment]
I'm experiencing this as well, on a Tablet running Windows 11, regardless of whether i'm using touch controls or a stylus. Ended up deleting the touch script itself, which didn't seem to break anything. Fixed the issue for me, but that's probably not the ideal solution.

**Comment by pythongosssss** [comment]
Touch events is removed as it should be semi-natively supported in ComfyUI now
